// SPDX-License-Identifier: AGPL-3.0-or-later
//! The API's types, generated from `proto/statemachined/v1/` and `proto/braemons/v1/`.
//!
//! **Nothing outside `grpc/` and `convert/` names a type from here.** These are
//! the shapes on the wire; `model/` holds the shapes this daemon thinks in, and
//! `convert/` is the seam between them. That is the same separation the Python
//! daemon keeps in `daemon/api/convert/`, and it is what lets a document on
//! disk and a message on a wire differ where they should.
//!
//! **The modules mirror the proto packages**, rather than being flattened the
//! way mousewheeld's single-package tree can afford to be: prost names a type
//! in the other package `super::super::braemons::v1::TrialOutcome`, and that
//! path only resolves if `statemachined::v1` and `braemons::v1` are siblings.
//!
//! Generated by `make proto` and **committed**, so a checkout builds with cargo
//! alone, a reviewer sees an interface change in a diff, and the types can be
//! read rather than inferred from a build directory. Do not edit by hand:
//! `make check-proto` regenerates and fails if the result differs.

#![allow(clippy::all)]

pub mod statemachined {
    pub mod v1 {
        include!("statemachined.v1.rs");

        /// The `service` blocks, as traits the daemon implements.
        ///
        /// **An rpc with no implementation is a compile error.** That is what
        /// `tests/unit/test_every_rpc_is_implemented.py` does for the Python
        /// daemon by reading the descriptor at runtime, moved to where the
        /// compiler can do it.
        pub mod service {
            #[allow(unused_imports)]
            use super::*;
            include!("service/statemachined.v1.rs");
        }
    }
}

/// The `.tdr` outcome taxonomy, which triald speaks too and neither daemon
/// owns. Vendored from `contracts/`; see `contracts/check_vendored_copies.py`.
pub mod braemons {
    pub mod v1 {
        include!("braemons.v1.rs");
    }
}

/// The schema, for server reflection.
///
/// How `grpcurl` and a client discover what this daemon speaks — every service,
/// every rpc, argument and return types — without having the `.proto` to hand.
/// The Python daemon does not offer this.
pub const DESCRIPTOR: &[u8] = include_bytes!("descriptor_for_reflection.bin");

/// The board's link, `proto/statemachined/link/v1/link.proto`, as a descriptor
/// set. Not the API: nothing here is served, and `device/link_codec.rs` is the
/// only reader.
pub const LINK_DESCRIPTOR: &[u8] = include_bytes!("link_descriptor.bin");
