// This file is @generated by prost-build.
/// Why a call was refused.
///
/// `detail` is meant to be shown to a person: it says what was wrong and, where
/// there is one, what to do instead. The gRPC status code carries the category —
/// `failed_precondition`, `invalid_argument`, `not_found`, `unavailable` — and
/// `error` names the particular case within it, which is what a client switches
/// on.
///
/// **`context` names what to change**, and it is the field that earns this
/// message its keep. A refusal that says `does_not_fit` tells somebody a graph
/// set is too big; one that also says `graphs` tells them where to look. The
/// rule comes from the device's own wire (`docs/reference/protocol.md` §5),
/// where every error carries a context, and it was worth keeping one layer up.
///
/// **A device's refusal is passed up with its own words.** When the board says
/// `graph_mismatch` or `busy` or `bad_index`, `error` is that code rather than
/// this daemon's paraphrase of it: those are the words the device's
/// documentation uses, and a caller switching on them should be switching on
/// the device's answer.
///
/// **A refusal travels as this message**, in the trailing metadata entry
/// `statemachined-error-bin`, rather than as a sentence for a client to parse.
/// The status message carries `detail (context)` as well, for grpcurl and logs.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    /// A short machine-readable kind: `not_connected`, `no_such_graph`,
    /// `does_not_fit`, or whatever the device itself said. Additive — new kinds
    /// appear, none change meaning.
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
    /// The field, graph or line the caller should look at. Never empty in
    /// practice: where there is nothing more specific it repeats `error`.
    #[prost(string, tag = "3")]
    pub context: ::prost::alloc::string::String,
}
/// What one board can hold, as `hello_ack` declares it.
///
/// **Read from the device, never assumed.** The reference board ships more than
/// one image and a Teensy is a different set of numbers again, so compiling
/// against a constant would mean a graph that fits in the tests and not on the
/// bench.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceCapacities {
    #[prost(int32, tag = "1")]
    pub max_line: i32,
    #[prost(int32, tag = "2")]
    pub max_states: i32,
    #[prost(int32, tag = "3")]
    pub max_transitions: i32,
    #[prost(int32, tag = "4")]
    pub max_output_actions: i32,
    #[prost(int32, tag = "5")]
    pub max_distributions: i32,
    #[prost(int32, tag = "6")]
    pub max_choice_options: i32,
    #[prost(int32, tag = "7")]
    pub max_path: i32,
    #[prost(int32, tag = "8")]
    pub max_graphs: i32,
    #[prost(int32, tag = "9")]
    pub max_timers: i32,
    /// Which input line the first global timer holds high. Not derivable from the
    /// line count: the timers are counted down from the top of the word, so that
    /// a graph means the same thing on a board with eight inputs and one with
    /// twenty. The device reports it because nothing else can know it.
    #[prost(int32, tag = "10")]
    pub first_timer_line: i32,
    #[prost(int32, tag = "11")]
    pub input_line_count: i32,
    #[prost(int32, tag = "12")]
    pub output_line_count: i32,
}
/// What a graph set costs a board, pool by pool.
///
/// **Six numbers and not one**, because a board has six pools and they fill
/// independently: a set can be two states short of the limit with room for
/// forty more transitions. One total would say "it does not fit" without
/// saying what to cut, which is the only part somebody setting up a session
/// can act on.
///
/// The same message carries usage and capacity, so the two are read the same
/// way and a panel puts them side by side without arithmetic. A pool the
/// firmware adds is a field added here, which is a diff a reviewer sees.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GraphPoolCounts {
    #[prost(int32, tag = "1")]
    pub graphs: i32,
    #[prost(int32, tag = "2")]
    pub states: i32,
    #[prost(int32, tag = "3")]
    pub transitions: i32,
    #[prost(int32, tag = "4")]
    pub output_actions: i32,
    #[prost(int32, tag = "5")]
    pub distributions: i32,
    #[prost(int32, tag = "6")]
    pub choice_options: i32,
}
/// The graph set the board is holding right now.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommittedGraphSet {
    #[prost(int32, tag = "1")]
    pub set_version: i32,
    #[prost(string, repeated, tag = "2")]
    pub graph_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub pool_usage: ::core::option::Option<GraphPoolCounts>,
    #[prost(message, optional, tag = "4")]
    pub pool_capacity: ::core::option::Option<GraphPoolCounts>,
}
/// How the serial link is behaving.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LinkHealth {
    /// How many times this daemon has opened the link since it started. A rig
    /// whose count climbs on its own has a cable or a power problem, and the
    /// number is the only thing that says so.
    #[prost(int32, tag = "1")]
    pub connection_count: i32,
    #[prost(int64, tag = "2")]
    pub dropped_lines: i64,
    #[prost(int64, tag = "3")]
    pub bad_lines: i64,
    #[prost(string, tag = "4")]
    pub last_error: ::prost::alloc::string::String,
}
/// Whether the board is keeping to its scan period.
///
/// **Diagnosis rather than control, and the honest half of the timing claim.**
/// A board that quietly misses scans looks exactly like one that is fine, so a
/// missed scan is counted and reported.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScanHealth {
    /// The rate the board is actually achieving, measured by the board.
    #[prost(int32, tag = "1")]
    pub hz: i32,
    /// Scans that took longer than the period. The number that makes a timing
    /// claim honest: a board quietly missing scans looks exactly like one that is
    /// fine.
    #[prost(int64, tag = "2")]
    pub overruns: i64,
    /// The worst gap seen, in scan periods.
    #[prost(int32, tag = "3")]
    pub worst_gap: i32,
    /// Times the board had something to say and could not, because the link was
    /// not draining. A rig whose `tx_stalls` climbs is losing trace entries at
    /// the far end rather than on the board.
    #[prost(int64, tag = "4")]
    pub tx_stalls: i64,
}
/// Everything about the attachment, in one answer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceState {
    #[prost(bool, tag = "1")]
    pub connected: bool,
    /// Where the daemon is told to look: a serial path, or a `socket://` URL for
    /// a board on a switch or the native build.
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub board: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub firmware_version: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub protocol_version: i32,
    #[prost(int32, tag = "6")]
    pub measured_scan_hz: i32,
    #[prost(message, optional, tag = "7")]
    pub capacities: ::core::option::Option<DeviceCapacities>,
    /// Whether the board has a wiring table of its own. Absent when nothing has
    /// said either way, which is a different thing from "no".
    #[prost(bool, optional, tag = "8")]
    pub has_wiring: ::core::option::Option<bool>,
    /// Whether this daemon knows which pin each line is **because the board said
    /// so**, or because it assumed. `docs/reference/protocol.md` §3.6, and the
    /// whole reason that command exists: before it, there was no third answer to
    /// "which pin is line 4" beyond a table copied out of the firmware.
    #[prost(string, tag = "9")]
    pub pin_labels_came_from: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub committed_set: ::core::option::Option<CommittedGraphSet>,
    #[prost(message, optional, tag = "11")]
    pub link: ::core::option::Option<LinkHealth>,
    #[prost(message, optional, tag = "12")]
    pub scan: ::core::option::Option<ScanHealth>,
    #[prost(int64, tag = "13")]
    pub uptime_device_microseconds: i64,
}
/// One input line: what it is called, how the rig conditions it, and what it
/// reads right now.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InputLine {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Which bit of the input word this is — the only part of a line that reaches
    /// the device. Absent when the map named a pin instead and there was no board
    /// to resolve it against; a line configured by pin reports the index it will
    /// actually be uploaded with as soon as one is attached.
    #[prost(int32, optional, tag = "2")]
    pub line_index: ::core::option::Option<i32>,
    /// The board's own name for that pin, which is what a person checks against
    /// the hardware.
    #[prost(string, tag = "3")]
    pub pin_label: ::prost::alloc::string::String,
    /// Reads active-low. Opto-isolated inputs routinely do, and it is applied
    /// when the word is assembled so that no predicate above it has a special
    /// case.
    #[prost(bool, tag = "4")]
    pub reads_active_low: bool,
    /// A disabled line reads zero however the pin is driven, which is how a rig
    /// says "nothing is plugged in there" without every graph having to avoid
    /// naming it.
    #[prost(bool, tag = "5")]
    pub is_enabled: bool,
    /// How long a change must hold before it is believed. Per line rather than
    /// per predicate, because a predicate over several lines is what chatters
    /// worst: two lines each bouncing once can make a combination rise and fall
    /// several times, and no care in the graph can filter that afterwards.
    ///
    /// In the view because it is part of the wiring somebody is looking at. It
    /// was left out of the first cut of this message, which made a rig's
    /// debouncing invisible to every reader of `ReadLines`.
    #[prost(int32, tag = "7")]
    pub debounce_milliseconds: i32,
    /// Its level right now, from the device's own `io` word. **The only way
    /// anything outside the device can check that a graph's line numbers reach
    /// the pins somebody wired** — there is no read-back path from a pin. Absent
    /// when nothing is attached, which is not the same as low.
    #[prost(bool, optional, tag = "6")]
    pub is_high_now: ::core::option::Option<bool>,
}
/// One output line: what it is called, and what "off" means for it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OutputLine {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, optional, tag = "2")]
    pub line_index: ::core::option::Option<i32>,
    #[prost(string, tag = "3")]
    pub pin_label: ::prost::alloc::string::String,
    /// The level this line is driven to on watchdog timeout, reset, link loss or
    /// a refused graph. **Per line, because "off" is not always "low":** an
    /// active-low valve driver is *opened* by a low, and a board that came up
    /// driving every line low would open it on every power cycle.
    #[prost(bool, tag = "4")]
    pub safe_level_is_high: bool,
    #[prost(bool, optional, tag = "5")]
    pub is_high_now: ::core::option::Option<bool>,
}
/// Every line this rig has, by name, with the board's answer folded in.
///
/// **A line map is a document somebody edits**, so replacing one carries its
/// text — `WriteLineMapFile` — and keeps its own schema
/// (`contracts/DAEMON_LAYOUT.md` §2). This is the *reading* of it that a panel
/// draws: the map, resolved against the board, with the live levels beside it.
/// That join is the one thing only the daemon can do.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LineMapView {
    #[prost(message, repeated, tag = "1")]
    pub input_lines: ::prost::alloc::vec::Vec<InputLine>,
    #[prost(message, repeated, tag = "2")]
    pub output_lines: ::prost::alloc::vec::Vec<OutputLine>,
    /// Where the pin labels came from. `device` means the board answered `pins`
    /// and these labels are its own; `assumed` means this daemon fell back to its
    /// own table for firmware older than that command, and every label here is a
    /// belief rather than a fact (`docs/reference/protocol.md` §3.6).
    #[prost(string, tag = "3")]
    pub pin_labels_came_from: ::prost::alloc::string::String,
    /// Indexed by line number, so a client reads the board's own name for line 4
    /// as `board_input_pins\[4\]`.
    #[prost(string, repeated, tag = "4")]
    pub board_input_pins: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "5")]
    pub board_output_pins: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// One line in or out of the serial port, in the protocol's own words.
///
/// **"Line" here is a line of text, not a GPIO line.** The two meanings collide
/// throughout this repository — `LineMap` is wiring and `DeviceLineMonitor` is
/// the port — so the interface says `Serial` where it means the port and keeps
/// `line` for the wire only inside this message, where the neighbouring
/// `direction` makes it unambiguous.
///
/// What this is for is the moment the layers stop agreeing: the line map says
/// the valve is line 3, the valve is not opening, and the question is whether
/// this daemon ever sent the command. Nothing else can answer it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SerialMonitorEntry {
    #[prost(int64, tag = "1")]
    pub entry_number: i64,
    /// `tx` or `rx`, from this daemon's point of view.
    #[prost(string, tag = "2")]
    pub direction: ::prost::alloc::string::String,
    /// The NDJSON exactly as it went, framing and all.
    #[prost(string, tag = "3")]
    pub line: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub recorded_host_time: ::prost::alloc::string::String,
}
/// A window of the serial monitor's ring.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SerialMonitorWindow {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<SerialMonitorEntry>,
    #[prost(int64, tag = "2")]
    pub newest_entry_number: i64,
    #[prost(int64, tag = "3")]
    pub oldest_entry_number_still_held: i64,
    #[prost(int32, tag = "4")]
    pub ring_capacity: i32,
    #[prost(int64, optional, tag = "5")]
    pub lost_entries_before: ::core::option::Option<i64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadSerialMonitorRequest {
    #[prost(int64, tag = "1")]
    pub since_entry_number: i64,
    #[prost(int32, tag = "2")]
    pub limit: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchSerialMonitorRequest {
    #[prost(int64, tag = "1")]
    pub since_entry_number: i64,
}
/// What replacing the line map did.
///
/// **Where it lands, and where it does not.** The map goes to the board and
/// into the loaded state-machine config *in memory*. It is not written to the
/// store until somebody saves that config, and this says so — because that is
/// the honest shape for a panel somebody is editing while watching a lamp: a
/// wiring change has to reach the board immediately to be *checked* against the
/// wire, and an edit that reached the disk on every keystroke would make
/// "revert" mean nothing.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteLineMapResult {
    #[prost(message, optional, tag = "1")]
    pub line_map: ::core::option::Option<LineMapView>,
    /// False when nothing is attached. The map is still kept, and still applies
    /// the moment a board greets.
    #[prost(bool, tag = "2")]
    pub pushed_to_device: bool,
    /// Always false today, and named rather than omitted: a UI has to be able to
    /// tell somebody their edit is one restart away from being lost.
    #[prost(bool, tag = "3")]
    pub saved_to_the_store: bool,
    /// Which config the map went into, or empty when none is loaded — a rig with
    /// no config takes the map anyway and has nowhere to save it.
    #[prost(string, tag = "4")]
    pub state_machine_config: ::prost::alloc::string::String,
}
/// What the board is running, and what could be flashed onto it.
/// What writing the board's settings to its own flash cost.
///
/// **`write_count` is a budget made visible.** Data flash wears out — about
/// 100,000 erase cycles on the reference board — and a rig a third of the way
/// through that budget should be able to say so rather than failing one day
/// with no warning.
///
/// **A save that would store what is already stored writes nothing**, answers
/// `written: false`, and leaves `write_count` where it was. It is answered
/// rather than refused: "it is already saved" is a success, and a save button
/// must not cost an erase cycle to press twice.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SaveSettingsResult {
    #[prost(bool, tag = "1")]
    pub written: bool,
    #[prost(int64, tag = "2")]
    pub write_count: i64,
    /// What was saved: whether there was a graph set, which version, and whether
    /// autorun was on. The three things that come back after a power cut.
    #[prost(bool, tag = "3")]
    pub has_set: bool,
    #[prost(int32, tag = "4")]
    pub set_version: i32,
    #[prost(bool, tag = "5")]
    pub autorun: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FirmwareVersions {
    /// What the board greeted with.
    #[prost(string, tag = "1")]
    pub running: ::prost::alloc::string::String,
    /// What this package ships, when it ships one.
    #[prost(string, tag = "2")]
    pub installed: ::prost::alloc::string::String,
    /// Whether the board names a stamped build at all. An unstamped image is a
    /// local build, and comparing it to anything is meaningless rather than
    /// false.
    #[prost(bool, tag = "3")]
    pub running_is_stamped: bool,
    /// Whether both sides name a stamped build, so the comparison means
    /// something.
    #[prost(bool, tag = "4")]
    pub comparable: bool,
    /// Only ever true when `comparable` is. **The comparison is the whole
    /// point**: a board in a rack cannot be asked which commit it is running, so
    /// the package carries a manifest and this says whether the two agree.
    #[prost(bool, tag = "5")]
    pub matches: bool,
}
/// Whether the board arms its own trials, and what it would run.
///
/// **This is the switch that makes the daemon optional**: the device starts
/// each run itself and waits out the dwell the terminal state it reached
/// declared. Asked of the board rather than remembered here — the setting is
/// stored on the device, outlives this daemon's session, and survives the
/// greeting that took the rig away from it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Autorun {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// `enabled` and `active` are not the same fact: a board can be configured to
    /// arm its own trials and not be doing so right now
    /// (`docs/reference/protocol.md` §3.7).
    #[prost(bool, tag = "2")]
    pub active: bool,
    /// Which graph it runs, by name where this daemon can say it. The board holds
    /// a slot; the name comes from the committed set.
    #[prost(string, tag = "3")]
    pub graph_name: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub slot: i32,
    #[prost(int32, tag = "5")]
    pub cap_milliseconds: i32,
    #[prost(int64, tag = "6")]
    pub seed: i64,
    #[prost(int64, tag = "7")]
    pub next_trial_id: i64,
}
/// Hand the board the job of arming its own trials, or take it back.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteAutorunRequest {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// A name, never a slot — like everything else this API takes. Left out when
    /// enabling, the session's active graph is used, which is the one a person
    /// looking at this rig would mean.
    #[prost(string, optional, tag = "2")]
    pub graph_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag = "3")]
    pub cap_milliseconds: i32,
    /// The stream the board's own trials draw from. Left out, whatever the board
    /// already holds stands — which for a board restored from its own storage is
    /// the seed that makes an unattended session replay.
    #[prost(int64, optional, tag = "4")]
    pub seed: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "5")]
    pub first_trial_id: ::core::option::Option<i64>,
    /// Whether to start arming trials now, or only to store the setting.
    ///
    /// **This is how a rig is actually set up**: enable, save, power cycle. A
    /// save is refused on a board that is running, and a board arming its own
    /// trials is never idle — so without a way to say "store it, do not start",
    /// the setting could never be written to flash. Unset means start, which is
    /// what an operator turning autorun on by hand means.
    #[prost(bool, optional, tag = "6")]
    pub start_now: ::core::option::Option<bool>,
}
/// One stored document: its name and its text.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoredFile {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadFileRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFileRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// A draft, for checking without storing it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileDraft {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
/// Enough of one stored graph to choose between them, without loading all of
/// them.
///
/// **A graph that no longer parses is listed as broken rather than omitted.** A
/// paradigm that has silently vanished from the list is how somebody spends an
/// afternoon looking for it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GraphSummary {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub readable: bool,
    /// Why it could not be read. Empty when it could.
    #[prost(string, tag = "3")]
    pub detail: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub state_count: i32,
    #[prost(string, tag = "5")]
    pub entry: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphSummaries {
    #[prost(message, repeated, tag = "1")]
    pub graphs: ::prost::alloc::vec::Vec<GraphSummary>,
}
/// What checking a graph found — every rule, plus **this board's** capacities.
///
/// The capacity half is the useful half: "you have room for two more graphs" is
/// what somebody setting up a session wants to know, and it is why this needs a
/// board attached and refuses `unavailable` without one.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphValidation {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    /// Why not. Empty when it is.
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub pool_usage: ::core::option::Option<GraphPoolCounts>,
    #[prost(message, optional, tag = "4")]
    pub pool_capacity: ::core::option::Option<GraphPoolCounts>,
    /// Legal, uploads, runs — and probably narrower than its author thinks.
    /// **Reported rather than refused**: a graph whose predicate can never be
    /// true is a paradigm somebody meant, right up until it is not.
    #[prost(message, repeated, tag = "5")]
    pub warnings: ::prost::alloc::vec::Vec<GraphWarning>,
}
/// One thing that is legal, runs exactly as written, and is probably not what
/// somebody meant.
///
/// **Structured and not a sentence**, because an editor puts it next to the
/// line that caused it: `state` and `transition` are where to put the marker,
/// and `detail` is what to say there. A string would have made the editor
/// parse English to find the place.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GraphWarning {
    /// What kind of warning, as a stable word to branch on:
    /// `any_clause_has_no_effect` is the one this daemon raises today.
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    /// Where. The state's name, and the transition's position within it — the
    /// position rather than a name because a transition has no name.
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub transition: i32,
    /// The lines the warning is about, by name.
    #[prost(string, repeated, tag = "4")]
    pub lines: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// One sentence, written to be read, usually ending in a question about what
    /// the author meant.
    #[prost(string, tag = "5")]
    pub detail: ::prost::alloc::string::String,
}
/// Enough of one stored state-machine config to choose between them.
///
/// Summaries rather than whole configs: a config carries its graphs, so ten of
/// them is most of a megabyte nobody is looking at yet. One that will not parse
/// is listed with the reason instead of omitted — a file you cannot see is a
/// file you cannot fix.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateMachineConfigSummary {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub readable: bool,
    #[prost(string, tag = "3")]
    pub detail: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub board: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub graph_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag = "7")]
    pub input_line_count: i32,
    #[prost(int32, tag = "8")]
    pub output_line_count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateMachineConfigSummaries {
    #[prost(message, repeated, tag = "1")]
    pub configs: ::prost::alloc::vec::Vec<StateMachineConfigSummary>,
    /// Which one this rig is loaded with, if any.
    #[prost(string, tag = "2")]
    pub loaded: ::prost::alloc::string::String,
}
/// What this rig is doing right now.
///
/// Small on purpose: this is the thing a panel polls and a console shows, and
/// everything in it is one read of the device's own state report. The whole
/// attachment — capacities, firmware, the committed set — is `Device/ReadDevice`
/// and changes on the scale of a session rather than a trial.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RigState {
    #[prost(bool, tag = "1")]
    pub connected: bool,
    /// The device's link state, as the device reports it: 0 idle, 1 armed,
    /// 2 running.
    #[prost(int32, tag = "2")]
    pub link_state: i32,
    #[prost(bool, tag = "3")]
    pub running: bool,
    #[prost(int64, optional, tag = "4")]
    pub trial_id: ::core::option::Option<i64>,
    /// The armed graph, by name.
    #[prost(string, tag = "5")]
    pub graph: ::prost::alloc::string::String,
    /// **By name where the daemon can say it**: an index means nothing to
    /// somebody watching a rig, and the daemon holds the graph. Absent when there
    /// is no committed set to resolve it against, which is a different thing from
    /// "state 0".
    #[prost(string, optional, tag = "6")]
    pub state_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "7")]
    pub state_index: ::core::option::Option<i32>,
    /// The device's input and output words, as bits. What a line monitor draws,
    /// and the only way to check that a graph's line numbers reach the pins
    /// somebody wired.
    #[prost(int64, optional, tag = "8")]
    pub input_word: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "9")]
    pub output_word: ::core::option::Option<i64>,
    #[prost(message, optional, tag = "10")]
    pub scan: ::core::option::Option<ScanHealth>,
    /// So a client can ask for what it has not seen without polling the ring.
    #[prost(int64, tag = "11")]
    pub newest_trace_entry_number: i64,
}
/// One thing that happened, as the trace recorded it.
///
/// **The payload is a `Struct` and that is deliberate.** A trace entry is
/// whatever the device said — a state visit, a line edge, a trial boundary, a
/// refusal — and the set grows with the firmware. Describing each kind here
/// would mean this daemon could not carry an entry from a board newer than
/// itself, which is exactly what a trace is for. `kind` says what it is; a
/// reader that does not know a kind shows it as itself rather than dropping it.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraceEntry {
    #[prost(int64, tag = "1")]
    pub entry_number: i64,
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
    /// When **this daemon** recorded it. Its own clock, and deliberately not an
    /// estimate of the device's: a visit's own device timestamp is in the
    /// payload, and conflating the two is how a trace stops being joinable to a
    /// record.
    #[prost(string, tag = "3")]
    pub recorded_host_time: ::prost::alloc::string::String,
    /// The trial this belongs to, when it belongs to one. Plenty do not — a line
    /// edge, a link event, a refusal.
    #[prost(int64, optional, tag = "4")]
    pub trial_id: ::core::option::Option<i64>,
    /// Everything else the entry carried.
    #[prost(message, optional, tag = "5")]
    pub payload: ::core::option::Option<::prost_types::Struct>,
}
/// A window of the trace's ring.
///
/// `lost_entries_before` is the one place the ring's boundedness is visible
/// from outside. Saying nothing would hand back a shorter answer that looks
/// complete, which is how a gap in a record becomes a gap in an analysis.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraceWindow {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<TraceEntry>,
    #[prost(int64, tag = "2")]
    pub newest_entry_number: i64,
    #[prost(int64, tag = "3")]
    pub oldest_entry_number_still_held: i64,
    #[prost(int32, tag = "4")]
    pub ring_capacity: i32,
    #[prost(int64, optional, tag = "5")]
    pub lost_entries_before: ::core::option::Option<i64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadTraceRequest {
    #[prost(int64, tag = "1")]
    pub since_entry_number: i64,
    #[prost(int32, tag = "2")]
    pub limit: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchTraceRequest {
    #[prost(int64, tag = "1")]
    pub since_entry_number: i64,
}
/// The trace of one trial, joined by `trial_id`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadTrialTraceRequest {
    #[prost(int64, tag = "1")]
    pub trial_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrialTrace {
    #[prost(int64, tag = "1")]
    pub trial_id: i64,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<TraceEntry>,
}
/// Who is watching this rig right now.
///
/// **A diagnostic, not a contract.** The daemon does not act on this list, does
/// not wait for anybody in it, and does not remember it across a restart — it
/// publishes and assumes nobody read it (`contracts/INTERACTIONS.md` §2). What
/// the list is for is the question a person asks when trials stop reaching
/// triald, which is otherwise answered with a packet capture.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Observer {
    #[prost(string, tag = "1")]
    pub observer_id: ::prost::alloc::string::String,
    /// What it called itself, when it said. Empty when it did not.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Which stream it is on: the state stream or the trace.
    #[prost(string, tag = "3")]
    pub stream: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub address: ::prost::alloc::string::String,
    #[prost(double, tag = "5")]
    pub connected_at_unix_seconds: f64,
    #[prost(double, tag = "6")]
    pub connected_seconds: f64,
    #[prost(int64, tag = "7")]
    pub delivered: i64,
    /// Whether this observer has ever been dropped a frame because it could not
    /// keep up. The number that answers "is the rig slow, or is that browser
    /// tab".
    #[prost(bool, tag = "8")]
    pub fell_behind: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Observers {
    #[prost(message, repeated, tag = "1")]
    pub observers: ::prost::alloc::vec::Vec<Observer>,
    #[prost(int32, tag = "2")]
    pub count: i32,
}
/// One frame of `WatchState`.
///
/// An envelope with a `oneof` in it, for the reason triald's has one: today
/// there is one arm, and a later message — a trace entry, a trial boundary —
/// can be added without every client having to learn a second stream.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateFrame {
    /// Monotonic; a gap means frames were coalesced, which is not loss: each
    /// frame is a whole state, so the newest is always the truth.
    #[prost(int64, tag = "1")]
    pub sequence: i64,
    #[prost(oneof = "state_frame::Frame", tags = "2")]
    pub frame: ::core::option::Option<state_frame::Frame>,
}
/// Nested message and enum types in `StateFrame`.
pub mod state_frame {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Frame {
        #[prost(message, tag = "2")]
        State(super::RigState),
    }
}
/// One stretch of a recording that was actually being written.
///
/// **A recording with a pause in it has no contiguous range of entry
/// numbers**, because the numbers are the trace's and the gap is real. The
/// segments are where that gap is written down; without them a reader would see
/// a jump and have to guess whether it was a pause or a loss.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordingSegment {
    #[prost(int64, optional, tag = "1")]
    pub from_entry_number: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "2")]
    pub to_entry_number: ::core::option::Option<i64>,
    #[prost(string, tag = "3")]
    pub started_host_time: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ended_host_time: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub entry_count: i64,
}
/// What a recording is, without its entries.
///
/// A manifest that will not parse is listed with its reason rather than
/// omitted, for the same reason a broken graph is: a file you cannot see is a
/// file you cannot fix.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordingManifest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// Which state-machine config the rig was running. Recorded because a trace
    /// means nothing without the graph set it was produced by.
    #[prost(string, tag = "3")]
    pub state_machine_config: ::prost::alloc::string::String,
    #[prost(double, tag = "4")]
    pub created_unix_seconds: f64,
    #[prost(string, tag = "5")]
    pub created_host_time: ::prost::alloc::string::String,
    /// `recording`, `paused` or `stopped`.
    #[prost(string, tag = "6")]
    pub state: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "7")]
    pub segments: ::prost::alloc::vec::Vec<RecordingSegment>,
    #[prost(int64, tag = "8")]
    pub entry_count: i64,
    /// How many entries of each kind, so a panel can say what is in a file
    /// without reading it.
    #[prost(btree_map = "string, int64", tag = "9")]
    pub kind_counts: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        i64,
    >,
    /// Why this manifest could not be read. Empty when it could, and the only
    /// field that is filled when it could not.
    #[prost(string, tag = "10")]
    pub unreadable: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Recordings {
    /// The one being written, if any.
    #[prost(message, optional, tag = "1")]
    pub active: ::core::option::Option<RecordingManifest>,
    #[prost(message, repeated, tag = "2")]
    pub recordings: ::prost::alloc::vec::Vec<RecordingManifest>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartRecordingRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordingName {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// The entries, **by position in the file** rather than by entry number.
///
/// By position because of the gap above: a recording with a pause in it has no
/// contiguous range of numbers to page through. Each entry still carries its
/// `entry_number`, so a reader can join it back to the trace exactly.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadRecordingEntriesRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub offset: i64,
    #[prost(int32, tag = "3")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordingEntries {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub offset: i64,
    #[prost(message, repeated, tag = "3")]
    pub entries: ::prost::alloc::vec::Vec<TraceEntry>,
    #[prost(int64, tag = "4")]
    pub entry_count: i64,
    #[prost(message, repeated, tag = "5")]
    pub segments: ::prost::alloc::vec::Vec<RecordingSegment>,
}
/// The box's own settings: which device, and how this daemon talks to it.
///
/// **The rig configuration, never a state-machine config.** The two are
/// unrelated and both were once called "config": this one changes when the
/// hardware does and lives in `/etc/braemons`, and a state-machine config is
/// one experiment's graphs and line map and changes per session. Every name
/// here says which.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RigConfiguration {
    /// The board. A serial path, or a `socket://` URL for one on a switch or the
    /// native build.
    #[prost(string, tag = "1")]
    pub device_target: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub device_baud: i32,
    #[prost(double, tag = "3")]
    pub device_timeout_seconds: f64,
    /// Refuse a board that is not this one. Empty accepts whatever answers, which
    /// is right for a bench and wrong for a rig with four of them on a bench
    /// beside it.
    #[prost(string, tag = "4")]
    pub expected_board: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub connect_on_startup: bool,
    /// Fixed for the life of the daemon when set, so that a whole session —
    /// including one interrupted by a reconnect — replays. Empty means one is
    /// drawn per connection, which is right for a rig and wrong for a
    /// reproduction.
    #[prost(string, tag = "14")]
    pub session_seed: ::prost::alloc::string::String,
    /// A config to load when the daemon starts, so a rig comes back up loaded
    /// rather than waiting for somebody to notice.
    #[prost(string, tag = "6")]
    pub startup_state_machine_config: ::prost::alloc::string::String,
    /// `set` uploads every graph once and selects per trial; `per_trial` uploads
    /// one each time. The first is how a session runs and the second is how a
    /// board too small for the set still runs it.
    #[prost(string, tag = "7")]
    pub graph_mode: ::prost::alloc::string::String,
    #[prost(int32, tag = "8")]
    pub trace_ring_entries: i32,
    #[prost(double, tag = "9")]
    pub heartbeat_seconds: f64,
    /// Where things are written. Empty `recording_directory` means nothing is
    /// recorded, which is right for a bench and wrong for a rig — so this says
    /// which it is rather than failing at the first `Recording/Start`.
    #[prost(string, tag = "10")]
    pub trace_directory: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub graph_store_directory: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub recording_directory: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub state_machine_config_directory: ::prost::alloc::string::String,
}
/// Change it, and do whatever the change implies.
///
/// **Until the daemon restarts.** This does not write `/etc/braemons`, on
/// purpose: a rig's configuration is a file somebody owns and reviews, and an
/// API that rewrote it would make the running daemon the authority on what the
/// box is. Every field is `optional`, so absent means "leave it alone".
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RigConfigurationPatch {
    #[prost(string, optional, tag = "1")]
    pub device_target: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "2")]
    pub device_baud: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub expected_board: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub graph_mode: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub startup_state_machine_config: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    /// See `RigConfiguration.session_seed`. Patchable because pinning it is what
    /// somebody does to reproduce a session, and an empty string is a value —
    /// "draw one per connection" — which is why this is `optional`.
    #[prost(string, optional, tag = "6")]
    pub session_seed: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RigConfigurationUpdate {
    #[prost(message, optional, tag = "1")]
    pub configuration: ::core::option::Option<RigConfiguration>,
    /// Whether the change reopened the link, which a changed `device_target`
    /// does.
    #[prost(bool, tag = "2")]
    pub reconnected: bool,
    /// Always true, and said out loud: nothing here survives a restart.
    #[prost(bool, tag = "3")]
    pub until_restart: bool,
}
/// What this rig is loaded with, and whether a session is open.
///
/// **Three separate facts, reported separately rather than collapsed into one
/// `ready` flag**, because the useful question at two in the morning is *which*
/// of them is missing: a config may be loaded with no session open, and a set
/// may be committed on the board from a session that ended — which is normal,
/// and is what makes a reconnect cheap.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionState {
    /// The loaded state-machine config, or nothing.
    #[prost(message, optional, tag = "1")]
    pub state_machine_config: ::core::option::Option<LoadedStateMachineConfig>,
    /// The graph set the board is holding, which may be from a session that has
    /// already ended.
    #[prost(message, optional, tag = "2")]
    pub committed_set: ::core::option::Option<CommittedGraphSet>,
    /// Whether a session is open on this connection.
    #[prost(bool, tag = "3")]
    pub session_open: bool,
    /// When it was opened, and how long ago. Absent when none is.
    ///
    /// `open_seconds` is computed here rather than left to a caller: a browser's
    /// clock and a rig's are not the same clock, and "open for 4 minutes" worked
    /// out from a timestamp difference across them is a number that goes negative
    /// on a box whose NTP has not settled.
    #[prost(double, optional, tag = "6")]
    pub opened_at_unix_seconds: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "7")]
    pub open_seconds: ::core::option::Option<f64>,
    /// Which graph a trial gets when it names none. Empty when nothing is
    /// selected, in which case a trial must name one.
    #[prost(string, tag = "4")]
    pub active_graph: ::prost::alloc::string::String,
    /// Every config in the store, by name, so a panel can offer them without a
    /// second call.
    #[prost(string, repeated, tag = "5")]
    pub stored_config_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoadedStateMachineConfig {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub board: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub graph_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Whether the config this rig is running is still in the store. A loaded
    /// config can be deleted while it is loaded, and the rig keeps running it —
    /// saying so is better than implying the store is the only place it exists.
    #[prost(bool, tag = "5")]
    pub still_in_the_store: bool,
}
/// Put the loaded config's graphs on the device.
///
/// **The slowest call in this API by a wide margin, and the one where a session
/// is allowed to fail**: a graph that does not fit this board fails here, with
/// an animal not yet in the booth, rather than at trial 40.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenSessionResult {
    #[prost(string, tag = "1")]
    pub state_machine_config: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub set_version: i32,
    /// Which slot each graph landed in. A caller never needs this — everything
    /// else in this API takes a name — but it is what a person compares against
    /// the board when a trial reports the wrong graph.
    #[prost(btree_map = "string, int32", tag = "3")]
    pub slots: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        i32,
    >,
    #[prost(message, optional, tag = "4")]
    pub pool_usage: ::core::option::Option<GraphPoolCounts>,
    #[prost(message, optional, tag = "5")]
    pub pool_capacity: ::core::option::Option<GraphPoolCounts>,
    #[prost(int32, tag = "6")]
    pub elapsed_milliseconds: i32,
}
/// Which graph a trial gets when it names none.
/// What closing a session did, beside the session it left behind.
///
/// **Closing cancels an armed trial**, and that is the one act it performs on
/// the board rather than in its own bookkeeping: an armed trial with nobody
/// driving it is a rig that will run one more trial at whatever time somebody
/// next touches a lever. Which trial that was is a fact the record needs, so it
/// is answered rather than only traced.
///
/// `was_open` distinguishes closing a session from closing nothing. Neither is
/// an error — closing twice is fine — and a caller that wanted to know which it
/// did could not tell from a `SessionState` that says `session_open: false`
/// either way.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CloseSessionResult {
    #[prost(bool, tag = "1")]
    pub was_open: bool,
    #[prost(int64, optional, tag = "2")]
    pub cancelled_trial_id: ::core::option::Option<i64>,
    /// The session as it now stands, so nothing has to read it back.
    #[prost(message, optional, tag = "3")]
    pub session: ::core::option::Option<SessionState>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetActiveGraphRequest {
    #[prost(string, tag = "1")]
    pub graph: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActiveGraph {
    /// Empty when nothing is selected.
    #[prost(string, tag = "1")]
    pub active_graph: ::prost::alloc::string::String,
}
/// What loading a state-machine config did.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoadedConfigResult {
    #[prost(string, tag = "1")]
    pub loaded: ::prost::alloc::string::String,
    /// Whether the wiring reached the board. A config loads with nothing
    /// attached — the line map is applied here and pushed when there is
    /// something to push.
    #[prost(bool, tag = "2")]
    pub wiring_pushed: bool,
    #[prost(message, optional, tag = "3")]
    pub line_map: ::core::option::Option<LineMapView>,
    #[prost(string, repeated, tag = "4")]
    pub graph_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// One state, entered and left, with everything the device measured about it.
///
/// **The indices are resolved into names here**, against the graph the trial
/// actually ran. That is what keeps a renamed state from silently mislabelling
/// last week's data, and it is why an analysis reads `Foreperiod` rather than
/// `state 2`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateVisit {
    #[prost(string, tag = "1")]
    pub state_name: ::prost::alloc::string::String,
    /// "timeout", "transition", "cancel" or "terminal".
    #[prost(string, tag = "2")]
    pub exit_cause: ::prost::alloc::string::String,
    /// Which of this state's transitions fired, counted from zero in the order
    /// the graph declares them. Absent for an exit that was not a transition —
    /// which is a different thing from transition zero, and the reason this is
    /// `optional` rather than a sentinel.
    #[prost(int32, optional, tag = "3")]
    pub fired_transition_position: ::core::option::Option<i32>,
    /// Where that transition led, resolved against the graph. Absent when nothing
    /// fired, and also when the graph this daemon holds no longer has that edge —
    /// an index the graph cannot explain is reported as unresolved rather than
    /// guessed at, because a row from a device holding a different set is a
    /// finding and a plausible name for it would bury that.
    #[prost(string, optional, tag = "4")]
    pub fired_transition_target_state_name: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    /// What the device *drew* for this state's timeout. Reported so that a random
    /// timing is evidence in the record rather than merely reproducible from the
    /// seed.
    #[prost(int32, tag = "5")]
    pub drawn_duration_ms: i32,
    /// Device clock. Wraps every ~71 minutes, which is why the daemon correlates
    /// it to the host clock rather than handing it over raw.
    #[prost(int64, tag = "6")]
    pub entered_device_microseconds: i64,
    /// What actually happened. `drawn_duration_ms` is what was asked for.
    #[prost(int64, tag = "7")]
    pub measured_duration_microseconds: i64,
}
/// A whole trial's result, reassembled and named.
///
/// **Nothing here is interpreted.** The daemon reports what the device measured
/// and sets no veto field; a record is evidence, and "not a second decision
/// authority" applies here more than anywhere, because a log is exactly where
/// an opinion gets smuggled in unnoticed. Whether a trial *counts* is triald's
/// question, asked of the same outcome.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrialResult {
    #[prost(int64, tag = "1")]
    pub trial_id: i64,
    /// The `.tdr` code. `braemons.v1` because neither this daemon nor triald owns
    /// the taxonomy: this one reports an outcome and that one records it.
    #[prost(enumeration = "super::super::braemons::v1::TrialOutcome", tag = "2")]
    pub outcome: i32,
    #[prost(enumeration = "TrialCancelReason", tag = "3")]
    pub cancel_reason: i32,
    #[prost(int64, tag = "4")]
    pub total_duration_microseconds: i64,
    #[prost(message, repeated, tag = "5")]
    pub visits: ::prost::alloc::vec::Vec<StateVisit>,
    /// **The device's path buffer is a ring.** A long looping trial arrives as a
    /// window rather than the whole run: `visits` holds the last of
    /// `total_visit_count`, starting at `first_visit_sequence_number`. Saying so
    /// is the only honest answer — a shorter list with no flag would look
    /// complete.
    #[prost(bool, tag = "6")]
    pub path_was_truncated: bool,
    #[prost(int64, tag = "7")]
    pub first_visit_sequence_number: i64,
    #[prost(int64, tag = "8")]
    pub total_visit_count: i64,
}
/// Which graph to run, and under what number.
///
/// `trial_id` addresses everything that follows: the start, the cancel and the
/// result all name it, so a result that arrives late is attributable rather
/// than assumed to belong to whatever is running now.
/// A per-trial override of one named distribution's parameters.
///
/// By **name**, like everything else a caller says. The daemon knows which
/// entry of the shared pool that name became — it built the set — and an index
/// on the caller's side would be a cache to get wrong across a re-upload.
///
/// Every parameter is `optional` because a patch is a patch: absent means
/// "leave this one alone", and zero is a legal duration.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DistributionPatch {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, optional, tag = "2")]
    pub minimum_ms: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub maximum_ms: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub mean_ms: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "5")]
    pub duration_ms: ::core::option::Option<i32>,
}
/// Arm the device for one trial of one graph. Nothing is uploaded.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigureTrialRequest {
    #[prost(int64, tag = "1")]
    pub trial_id: i64,
    /// A name, never a slot. Empty means the **active graph**, which is what a
    /// person pressing a button on a bench means. triald never relies on it: it
    /// names a graph every trial, and a name given here always wins over the
    /// selection.
    #[prost(string, tag = "2")]
    pub graph: ::prost::alloc::string::String,
    /// A wall-clock cap on the whole trial, `0` for none. It stays whatever the
    /// graph says, because validation cannot tell a ten-second foreperiod from a
    /// hang.
    #[prost(int32, tag = "3")]
    pub cap_milliseconds: i32,
    /// What starts the trial: `serial` (the host says go) or `line` (an input
    /// edge does).
    #[prost(string, tag = "4")]
    pub start_source: ::prost::alloc::string::String,
    /// The input line whose rising edge starts the trial. Required when
    /// `start_source` is `line`, ignored otherwise, and refused by the device if
    /// the board does not have it or the wiring has it disabled. `optional`
    /// because line 0 is a real line.
    #[prost(int32, optional, tag = "5")]
    pub start_line: ::core::option::Option<i32>,
    #[prost(message, repeated, tag = "6")]
    pub distribution_patches: ::prost::alloc::vec::Vec<DistributionPatch>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigureTrialResult {
    #[prost(int64, tag = "1")]
    pub trial_id: i64,
    #[prost(string, tag = "2")]
    pub graph: ::prost::alloc::string::String,
    /// Which committed set this trial was armed against, and where in it the
    /// graph sits. Reported because a mismatch between these and what the board
    /// later says it ran is the failure the whole addressing scheme exists to
    /// catch.
    #[prost(int32, tag = "3")]
    pub set_version: i32,
    #[prost(int32, tag = "4")]
    pub graph_index: i32,
    /// How long arming took. Reported whether or not it was slow, so that an arm
    /// which took longer than it should is a number per trial rather than an
    /// inference from a trial that started late.
    #[prost(int32, tag = "5")]
    pub elapsed_milliseconds: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartTrialRequest {
    #[prost(int64, tag = "1")]
    pub trial_id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartTrialResult {
    #[prost(int64, tag = "1")]
    pub trial_id: i64,
    #[prost(int64, tag = "2")]
    pub started_device_microseconds: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelTrialRequest {
    #[prost(int64, tag = "1")]
    pub trial_id: i64,
}
/// What a trial in flight is doing, or nothing when none is.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadTrialResultRequest {
    /// Which trial's result to read. Absent means the most recent one.
    #[prost(int64, optional, tag = "1")]
    pub trial_id: ::core::option::Option<i64>,
}
/// How a trial was cancelled, when it was.
///
/// Mirrors `statemachined.model.trial_outcome.TrialCancelReason`. Separate from
/// the outcome because `CANCELLED` is *what* happened and this is *why*: a
/// trial the host abandoned and one the device gave up on are the same outcome
/// and different findings.
/// The device's own account, not something a graph declares: only `HOST` ever
/// comes from outside, and the rest are things only the device can observe.
///
/// The numbers are the device's, from `result_begin.cancel_reason`, and are as
/// much a wire contract as the outcome codes — they are in every record this
/// daemon has written.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TrialCancelReason {
    None = 0,
    /// The host asked. The only one that comes from outside the device.
    Host = 1,
    LinkLost = 2,
    AbortLine = 3,
    TrialTimeout = 4,
}
impl TrialCancelReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "TRIAL_CANCEL_REASON_NONE",
            Self::Host => "TRIAL_CANCEL_REASON_HOST",
            Self::LinkLost => "TRIAL_CANCEL_REASON_LINK_LOST",
            Self::AbortLine => "TRIAL_CANCEL_REASON_ABORT_LINE",
            Self::TrialTimeout => "TRIAL_CANCEL_REASON_TRIAL_TIMEOUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRIAL_CANCEL_REASON_NONE" => Some(Self::None),
            "TRIAL_CANCEL_REASON_HOST" => Some(Self::Host),
            "TRIAL_CANCEL_REASON_LINK_LOST" => Some(Self::LinkLost),
            "TRIAL_CANCEL_REASON_ABORT_LINE" => Some(Self::AbortLine),
            "TRIAL_CANCEL_REASON_TRIAL_TIMEOUT" => Some(Self::TrialTimeout),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadStateRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchStateRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadObserversRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadDeviceRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenLinkRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadLinesRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadFirmwareRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadAutorunRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SaveSettingsRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListGraphsRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListConfigsRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadSessionRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadGraphsRequest {
    /// By name, in the order they should occupy slots. An empty list is refused
    /// rather than treated as "clear": giving a board nothing to run is
    /// `Session/Close`, and the two are different intentions.
    #[prost(string, repeated, tag = "1")]
    pub graph_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenSessionRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseSessionRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearActiveGraphRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadRecordingsRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PauseRecordingRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeRecordingRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopRecordingRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearRecordingRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadConfigurationRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadHealthRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Health {
    /// Always true: a daemon that could not answer would not have.
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(bool, tag = "2")]
    pub device_connected: bool,
}
/// What a cancel actually did.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelTrialResult {
    #[prost(int64, tag = "1")]
    pub trial_id: i64,
    /// Whether the device cancelled it. False when the trial had already ended,
    /// in which case `outcome` is the real one.
    #[prost(bool, tag = "2")]
    pub cancelled: bool,
    /// The outcome the device reports, which is not necessarily `CANCELLED`.
    #[prost(int32, tag = "3")]
    pub outcome_code: i32,
}
