# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statemachined/v1/rig_configuration.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'statemachined/v1/rig_configuration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(statemachined/v1/rig_configuration.proto\x12\x10statemachined.v1\"\x80\x03\n\x10RigConfiguration\x12\x15\n\rdevice_target\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_baud\x18\x02 \x01(\x05\x12\x1e\n\x16\x64\x65vice_timeout_seconds\x18\x03 \x01(\x01\x12\x16\n\x0e\x65xpected_board\x18\x04 \x01(\t\x12\x1a\n\x12\x63onnect_on_startup\x18\x05 \x01(\x08\x12$\n\x1cstartup_state_machine_config\x18\x06 \x01(\t\x12\x12\n\ngraph_mode\x18\x07 \x01(\t\x12\x1a\n\x12trace_ring_entries\x18\x08 \x01(\x05\x12\x19\n\x11heartbeat_seconds\x18\t \x01(\x01\x12\x17\n\x0ftrace_directory\x18\n \x01(\t\x12\x1d\n\x15graph_store_directory\x18\x0b \x01(\t\x12\x1b\n\x13recording_directory\x18\x0c \x01(\t\x12&\n\x1estate_machine_config_directory\x18\r \x01(\t\"\x93\x02\n\x15RigConfigurationPatch\x12\x1a\n\rdevice_target\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65vice_baud\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x1b\n\x0e\x65xpected_board\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\ngraph_mode\x18\x04 \x01(\tH\x03\x88\x01\x01\x12)\n\x1cstartup_state_machine_config\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\x10\n\x0e_device_targetB\x0e\n\x0c_device_baudB\x11\n\x0f_expected_boardB\r\n\x0b_graph_modeB\x1f\n\x1d_startup_state_machine_config\"\x7f\n\x16RigConfigurationUpdate\x12\x39\n\rconfiguration\x18\x01 \x01(\x0b\x32\".statemachined.v1.RigConfiguration\x12\x13\n\x0breconnected\x18\x02 \x01(\x08\x12\x15\n\runtil_restart\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statemachined.v1.rig_configuration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RIGCONFIGURATION']._serialized_start=63
  _globals['_RIGCONFIGURATION']._serialized_end=447
  _globals['_RIGCONFIGURATIONPATCH']._serialized_start=450
  _globals['_RIGCONFIGURATIONPATCH']._serialized_end=725
  _globals['_RIGCONFIGURATIONUPDATE']._serialized_start=727
  _globals['_RIGCONFIGURATIONUPDATE']._serialized_end=854
# @@protoc_insertion_point(module_scope)
