# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statemachined/v1/session.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'statemachined/v1/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from statemachined._proto.statemachined.v1 import device_pb2 as statemachined_dot_v1_dot_device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1estatemachined/v1/session.proto\x12\x10statemachined.v1\x1a\x1dstatemachined/v1/device.proto\"\xdd\x01\n\x0cSessionState\x12H\n\x14state_machine_config\x18\x01 \x01(\x0b\x32*.statemachined.v1.LoadedStateMachineConfig\x12:\n\rcommitted_set\x18\x02 \x01(\x0b\x32#.statemachined.v1.CommittedGraphSet\x12\x14\n\x0csession_open\x18\x03 \x01(\x08\x12\x14\n\x0c\x61\x63tive_graph\x18\x04 \x01(\t\x12\x1b\n\x13stored_config_names\x18\x05 \x03(\t\"}\n\x18LoadedStateMachineConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05\x62oard\x18\x03 \x01(\t\x12\x13\n\x0bgraph_names\x18\x04 \x03(\t\x12\x1a\n\x12still_in_the_store\x18\x05 \x01(\x08\"\xfc\x01\n\x11OpenSessionResult\x12\x1c\n\x14state_machine_config\x18\x01 \x01(\t\x12\x13\n\x0bset_version\x18\x02 \x01(\x05\x12=\n\x05slots\x18\x03 \x03(\x0b\x32..statemachined.v1.OpenSessionResult.SlotsEntry\x12\x12\n\npool_usage\x18\x04 \x01(\x05\x12\x15\n\rpool_capacity\x18\x05 \x01(\x05\x12\x1c\n\x14\x65lapsed_milliseconds\x18\x06 \x01(\x05\x1a,\n\nSlotsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"&\n\x15SetActiveGraphRequest\x12\r\n\x05graph\x18\x01 \x01(\t\"#\n\x0b\x41\x63tiveGraph\x12\x14\n\x0c\x61\x63tive_graph\x18\x01 \x01(\t\"\x81\x01\n\x12LoadedConfigResult\x12\x0e\n\x06loaded\x18\x01 \x01(\t\x12\x15\n\rwiring_pushed\x18\x02 \x01(\x08\x12/\n\x08line_map\x18\x03 \x01(\x0b\x32\x1d.statemachined.v1.LineMapView\x12\x13\n\x0bgraph_names\x18\x04 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statemachined.v1.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENSESSIONRESULT_SLOTSENTRY']._loaded_options = None
  _globals['_OPENSESSIONRESULT_SLOTSENTRY']._serialized_options = b'8\001'
  _globals['_SESSIONSTATE']._serialized_start=84
  _globals['_SESSIONSTATE']._serialized_end=305
  _globals['_LOADEDSTATEMACHINECONFIG']._serialized_start=307
  _globals['_LOADEDSTATEMACHINECONFIG']._serialized_end=432
  _globals['_OPENSESSIONRESULT']._serialized_start=435
  _globals['_OPENSESSIONRESULT']._serialized_end=687
  _globals['_OPENSESSIONRESULT_SLOTSENTRY']._serialized_start=643
  _globals['_OPENSESSIONRESULT_SLOTSENTRY']._serialized_end=687
  _globals['_SETACTIVEGRAPHREQUEST']._serialized_start=689
  _globals['_SETACTIVEGRAPHREQUEST']._serialized_end=727
  _globals['_ACTIVEGRAPH']._serialized_start=729
  _globals['_ACTIVEGRAPH']._serialized_end=764
  _globals['_LOADEDCONFIGRESULT']._serialized_start=767
  _globals['_LOADEDCONFIGRESULT']._serialized_end=896
# @@protoc_insertion_point(module_scope)
