# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statemachined/v1/session.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'statemachined/v1/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from statemachined._proto.statemachined.v1 import device_pb2 as statemachined_dot_v1_dot_device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1estatemachined/v1/session.proto\x12\x10statemachined.v1\x1a\x1dstatemachined/v1/device.proto\"\xb3\x02\n\x0cSessionState\x12^\n\x14state_machine_config\x18\x01 \x01(\x0b\x32*.statemachined.v1.LoadedStateMachineConfigR\x14state_machine_config\x12I\n\rcommitted_set\x18\x02 \x01(\x0b\x32#.statemachined.v1.CommittedGraphSetR\rcommitted_set\x12\"\n\x0csession_open\x18\x03 \x01(\x08R\x0csession_open\x12\"\n\x0c\x61\x63tive_graph\x18\x04 \x01(\tR\x0c\x61\x63tive_graph\x12\x30\n\x13stored_config_names\x18\x05 \x03(\tR\x13stored_config_names\"\x9e\x01\n\x18LoadedStateMachineConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05\x62oard\x18\x03 \x01(\t\x12 \n\x0bgraph_names\x18\x04 \x03(\tR\x0bgraph_names\x12.\n\x12still_in_the_store\x18\x05 \x01(\x08R\x12still_in_the_store\"\xd0\x02\n\x11OpenSessionResult\x12\x32\n\x14state_machine_config\x18\x01 \x01(\tR\x14state_machine_config\x12 \n\x0bset_version\x18\x02 \x01(\x05R\x0bset_version\x12=\n\x05slots\x18\x03 \x03(\x0b\x32..statemachined.v1.OpenSessionResult.SlotsEntry\x12\x1e\n\npool_usage\x18\x04 \x01(\x05R\npool_usage\x12$\n\rpool_capacity\x18\x05 \x01(\x05R\rpool_capacity\x12\x32\n\x14\x65lapsed_milliseconds\x18\x06 \x01(\x05R\x14\x65lapsed_milliseconds\x1a,\n\nSlotsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"&\n\x15SetActiveGraphRequest\x12\r\n\x05graph\x18\x01 \x01(\t\"1\n\x0b\x41\x63tiveGraph\x12\"\n\x0c\x61\x63tive_graph\x18\x01 \x01(\tR\x0c\x61\x63tive_graph\"\xa7\x01\n\x12LoadedConfigResult\x12\x0e\n\x06loaded\x18\x01 \x01(\t\x12$\n\rwiring_pushed\x18\x02 \x01(\x08R\rwiring_pushed\x12\x39\n\x08line_map\x18\x03 \x01(\x0b\x32\x1d.statemachined.v1.LineMapViewR\x08line_map\x12 \n\x0bgraph_names\x18\x04 \x03(\tR\x0bgraph_namesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statemachined.v1.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENSESSIONRESULT_SLOTSENTRY']._loaded_options = None
  _globals['_OPENSESSIONRESULT_SLOTSENTRY']._serialized_options = b'8\001'
  _globals['_SESSIONSTATE']._serialized_start=84
  _globals['_SESSIONSTATE']._serialized_end=391
  _globals['_LOADEDSTATEMACHINECONFIG']._serialized_start=394
  _globals['_LOADEDSTATEMACHINECONFIG']._serialized_end=552
  _globals['_OPENSESSIONRESULT']._serialized_start=555
  _globals['_OPENSESSIONRESULT']._serialized_end=891
  _globals['_OPENSESSIONRESULT_SLOTSENTRY']._serialized_start=847
  _globals['_OPENSESSIONRESULT_SLOTSENTRY']._serialized_end=891
  _globals['_SETACTIVEGRAPHREQUEST']._serialized_start=893
  _globals['_SETACTIVEGRAPHREQUEST']._serialized_end=931
  _globals['_ACTIVEGRAPH']._serialized_start=933
  _globals['_ACTIVEGRAPH']._serialized_end=982
  _globals['_LOADEDCONFIGRESULT']._serialized_start=985
  _globals['_LOADEDCONFIGRESULT']._serialized_end=1152
# @@protoc_insertion_point(module_scope)
