/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "statemachined/link/v1/link.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(statemachined_link_v1_HostMessage, statemachined_link_v1_HostMessage, 2)


PB_BIND(statemachined_link_v1_DeviceMessage, statemachined_link_v1_DeviceMessage, 2)


PB_BIND(statemachined_link_v1_Hello, statemachined_link_v1_Hello, AUTO)


PB_BIND(statemachined_link_v1_SetBegin, statemachined_link_v1_SetBegin, AUTO)


PB_BIND(statemachined_link_v1_SetEnd, statemachined_link_v1_SetEnd, AUTO)


PB_BIND(statemachined_link_v1_GraphBegin, statemachined_link_v1_GraphBegin, AUTO)


PB_BIND(statemachined_link_v1_GraphDist, statemachined_link_v1_GraphDist, 2)


PB_BIND(statemachined_link_v1_Timeout, statemachined_link_v1_Timeout, AUTO)


PB_BIND(statemachined_link_v1_GraphState, statemachined_link_v1_GraphState, AUTO)


PB_BIND(statemachined_link_v1_GraphTransition, statemachined_link_v1_GraphTransition, AUTO)


PB_BIND(statemachined_link_v1_GraphAction, statemachined_link_v1_GraphAction, AUTO)


PB_BIND(statemachined_link_v1_GraphTimer, statemachined_link_v1_GraphTimer, AUTO)


PB_BIND(statemachined_link_v1_GraphEnd, statemachined_link_v1_GraphEnd, AUTO)


PB_BIND(statemachined_link_v1_Patch, statemachined_link_v1_Patch, AUTO)


PB_BIND(statemachined_link_v1_Configure, statemachined_link_v1_Configure, 2)


PB_BIND(statemachined_link_v1_Start, statemachined_link_v1_Start, AUTO)


PB_BIND(statemachined_link_v1_Cancel, statemachined_link_v1_Cancel, AUTO)


PB_BIND(statemachined_link_v1_Ping, statemachined_link_v1_Ping, AUTO)


PB_BIND(statemachined_link_v1_StateRequest, statemachined_link_v1_StateRequest, AUTO)


PB_BIND(statemachined_link_v1_Wiring, statemachined_link_v1_Wiring, AUTO)


PB_BIND(statemachined_link_v1_Timers, statemachined_link_v1_Timers, AUTO)


PB_BIND(statemachined_link_v1_Pins, statemachined_link_v1_Pins, AUTO)


PB_BIND(statemachined_link_v1_Autorun, statemachined_link_v1_Autorun, AUTO)


PB_BIND(statemachined_link_v1_Save, statemachined_link_v1_Save, AUTO)


PB_BIND(statemachined_link_v1_Caps, statemachined_link_v1_Caps, AUTO)


PB_BIND(statemachined_link_v1_HelloAck, statemachined_link_v1_HelloAck, AUTO)


PB_BIND(statemachined_link_v1_Ack, statemachined_link_v1_Ack, AUTO)


PB_BIND(statemachined_link_v1_SetOk, statemachined_link_v1_SetOk, AUTO)


PB_BIND(statemachined_link_v1_Armed, statemachined_link_v1_Armed, AUTO)


PB_BIND(statemachined_link_v1_Started, statemachined_link_v1_Started, AUTO)


PB_BIND(statemachined_link_v1_CancelAck, statemachined_link_v1_CancelAck, AUTO)


PB_BIND(statemachined_link_v1_StateVisit, statemachined_link_v1_StateVisit, AUTO)


PB_BIND(statemachined_link_v1_ResultBegin, statemachined_link_v1_ResultBegin, AUTO)


PB_BIND(statemachined_link_v1_ResultPath, statemachined_link_v1_ResultPath, 2)


PB_BIND(statemachined_link_v1_ResultEnd, statemachined_link_v1_ResultEnd, AUTO)


PB_BIND(statemachined_link_v1_Event, statemachined_link_v1_Event, AUTO)


PB_BIND(statemachined_link_v1_Error, statemachined_link_v1_Error, AUTO)


PB_BIND(statemachined_link_v1_Log, statemachined_link_v1_Log, AUTO)


PB_BIND(statemachined_link_v1_Pong, statemachined_link_v1_Pong, AUTO)


PB_BIND(statemachined_link_v1_GraphReport, statemachined_link_v1_GraphReport, AUTO)


PB_BIND(statemachined_link_v1_IoReport, statemachined_link_v1_IoReport, AUTO)


PB_BIND(statemachined_link_v1_ScanReport, statemachined_link_v1_ScanReport, AUTO)


PB_BIND(statemachined_link_v1_StateReport, statemachined_link_v1_StateReport, AUTO)


PB_BIND(statemachined_link_v1_Visit, statemachined_link_v1_Visit, AUTO)


PB_BIND(statemachined_link_v1_PinMap, statemachined_link_v1_PinMap, 2)


PB_BIND(statemachined_link_v1_AutorunOk, statemachined_link_v1_AutorunOk, AUTO)


PB_BIND(statemachined_link_v1_Saved, statemachined_link_v1_Saved, AUTO)

















