/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_STATEMACHINED_LINK_V1_STATEMACHINED_LINK_V1_LINK_PB_H_INCLUDED
#define PB_STATEMACHINED_LINK_V1_STATEMACHINED_LINK_V1_LINK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _statemachined_link_v1_DistKind {
    statemachined_link_v1_DistKind_DIST_KIND_UNSPECIFIED = 0,
    statemachined_link_v1_DistKind_DIST_KIND_FIXED = 1,
    statemachined_link_v1_DistKind_DIST_KIND_UNIFORM = 2,
    statemachined_link_v1_DistKind_DIST_KIND_EXPONENTIAL = 3,
    statemachined_link_v1_DistKind_DIST_KIND_CHOICE = 4
} statemachined_link_v1_DistKind;

typedef enum _statemachined_link_v1_ActionOn {
    statemachined_link_v1_ActionOn_ACTION_ON_UNSPECIFIED = 0,
    statemachined_link_v1_ActionOn_ACTION_ON_ENTRY = 1,
    statemachined_link_v1_ActionOn_ACTION_ON_EXIT = 2
} statemachined_link_v1_ActionOn;

typedef enum _statemachined_link_v1_ActionKind {
    statemachined_link_v1_ActionKind_ACTION_KIND_UNSPECIFIED = 0,
    statemachined_link_v1_ActionKind_ACTION_KIND_HIGH = 1,
    statemachined_link_v1_ActionKind_ACTION_KIND_LOW = 2,
    statemachined_link_v1_ActionKind_ACTION_KIND_TOGGLE = 3,
    statemachined_link_v1_ActionKind_ACTION_KIND_PULSE = 4,
    statemachined_link_v1_ActionKind_ACTION_KIND_TIMER_START = 5,
    statemachined_link_v1_ActionKind_ACTION_KIND_TIMER_CANCEL = 6
} statemachined_link_v1_ActionKind;

typedef enum _statemachined_link_v1_StartSource {
    statemachined_link_v1_StartSource_START_SOURCE_UNSPECIFIED = 0,
    statemachined_link_v1_StartSource_START_SOURCE_SERIAL = 1,
    statemachined_link_v1_StartSource_START_SOURCE_LINE = 2,
    statemachined_link_v1_StartSource_START_SOURCE_BOTH = 3
} statemachined_link_v1_StartSource;

typedef enum _statemachined_link_v1_CancelReason {
    statemachined_link_v1_CancelReason_CANCEL_REASON_UNSPECIFIED = 0,
    statemachined_link_v1_CancelReason_CANCEL_REASON_HOST = 1,
    statemachined_link_v1_CancelReason_CANCEL_REASON_LINK_LOST = 2,
    statemachined_link_v1_CancelReason_CANCEL_REASON_ABORT_LINE = 3,
    statemachined_link_v1_CancelReason_CANCEL_REASON_TRIAL_TIMEOUT = 4
} statemachined_link_v1_CancelReason;

typedef enum _statemachined_link_v1_Direction {
    statemachined_link_v1_Direction_DIRECTION_UNSPECIFIED = 0,
    statemachined_link_v1_Direction_DIRECTION_IN = 1,
    statemachined_link_v1_Direction_DIRECTION_OUT = 2
} statemachined_link_v1_Direction;

typedef enum _statemachined_link_v1_ExitCause {
    statemachined_link_v1_ExitCause_EXIT_CAUSE_UNSPECIFIED = 0,
    statemachined_link_v1_ExitCause_EXIT_CAUSE_TIMEOUT = 1,
    statemachined_link_v1_ExitCause_EXIT_CAUSE_TRANSITION = 2,
    statemachined_link_v1_ExitCause_EXIT_CAUSE_CANCEL = 3,
    statemachined_link_v1_ExitCause_EXIT_CAUSE_TERMINAL = 4
} statemachined_link_v1_ExitCause;

/* Struct definitions */
typedef struct _statemachined_link_v1_Hello {
    /* Protocol version. **2**: the NDJSON wire was 1. */
    uint32_t proto;
    /* The session seed. Every per-trial stream is derived from it and the
 `trial_id`. A 64-bit integer at last, rather than the hex string a JSON
 number could not carry. */
    uint64_t seed;
} statemachined_link_v1_Hello;

typedef struct _statemachined_link_v1_SetBegin {
    uint32_t set_version;
    uint32_t n_graphs;
} statemachined_link_v1_SetBegin;

typedef struct _statemachined_link_v1_SetEnd {
    uint32_t n_states;
    uint32_t n_transitions;
    uint32_t n_output_actions;
    /* CRC-16/CCITT-FALSE over the protobuf bytes of every upload message since
 `set_begin`, `set_begin` included and this one excluded. Catches a missing
 message, which no per-frame CRC can see. */
    uint32_t checksum;
} statemachined_link_v1_SetEnd;

typedef struct _statemachined_link_v1_GraphBegin {
    uint32_t slot;
    uint32_t n_states;
    /* Within this graph. */
    uint32_t entry;
} statemachined_link_v1_GraphBegin;

typedef struct _statemachined_link_v1_GraphDist {
    uint32_t i;
    statemachined_link_v1_DistKind kind;
    /* Milliseconds. What each means depends on `kind`: see §3.2. */
    int32_t a;
    int32_t b;
    int32_t c;
    /* `choice` only. */
    pb_size_t opts_count;
    int32_t opts[32];
    /* `choice` only, and optional: empty means every option weighs 1. */
    pb_size_t weights_count;
    uint32_t weights[32];
} statemachined_link_v1_GraphDist;

typedef struct _statemachined_link_v1_Timeout {
    /* A distribution, set-global. */
    uint32_t dist;
    /* A state, within this graph. */
    uint32_t target;
} statemachined_link_v1_Timeout;

typedef struct _statemachined_link_v1_GraphState {
    uint32_t i;
    /* The outcome code this state reports. Absent on a state that is not
 terminal. */
    bool has_terminal;
    int32_t terminal;
    bool has_timeout;
    statemachined_link_v1_Timeout timeout;
    /* Terminal states only: the distribution the dwell before another run is
 drawn from. Absent means none. */
    bool has_relight;
    uint32_t relight;
} statemachined_link_v1_GraphState;

typedef struct _statemachined_link_v1_GraphTransition {
    uint32_t all;
    uint32_t any;
    uint32_t none;
    uint32_t target;
    /* A distribution. Absent means the predicate fires the scan it holds. */
    bool has_hold;
    uint32_t hold;
    bool level;
} statemachined_link_v1_GraphTransition;

typedef struct _statemachined_link_v1_GraphAction {
    statemachined_link_v1_ActionOn on;
    /* An output line. Not read by the timer kinds. */
    uint32_t line;
    statemachined_link_v1_ActionKind kind;
    /* `pulse` only. */
    uint32_t ms;
    /* `timer_start` / `timer_cancel` only. */
    uint32_t timer;
} statemachined_link_v1_GraphAction;

typedef struct _statemachined_link_v1_GraphTimer {
    uint32_t i;
    uint32_t width;
    bool has_delay;
    uint32_t delay;
    bool has_gap;
    uint32_t gap;
    bool has_line;
    uint32_t line;
    /* Absent means 1; 0 runs until something stops it. */
    bool has_loops;
    uint32_t loops;
    uint32_t all;
    uint32_t any;
    uint32_t none;
    bool active_low;
    bool trial_bound;
} statemachined_link_v1_GraphTimer;

typedef struct _statemachined_link_v1_GraphEnd {
    uint32_t n_transitions;
    uint32_t n_output_actions;
} statemachined_link_v1_GraphEnd;

typedef struct _statemachined_link_v1_Patch {
    uint32_t i;
    bool has_a;
    int32_t a;
    bool has_b;
    int32_t b;
    bool has_c;
    int32_t c;
} statemachined_link_v1_Patch;

typedef struct _statemachined_link_v1_Configure {
    uint32_t trial_id;
    uint32_t set_version;
    uint32_t graph_index;
    int32_t cap_ms;
    /* Unspecified is `serial`. */
    statemachined_link_v1_StartSource start;
    /* Required when `start` admits a line. */
    bool has_start_line;
    uint32_t start_line;
    /* Absent leaves the device's own mask in force. */
    bool has_timers;
    uint32_t timers;
    pb_size_t patch_count;
    statemachined_link_v1_Patch patch[8];
} statemachined_link_v1_Configure;

typedef struct _statemachined_link_v1_Start {
    uint32_t trial_id;
} statemachined_link_v1_Start;

typedef struct _statemachined_link_v1_Cancel {
    uint32_t trial_id;
    /* Only `host` is the host's to give. Unspecified is `host`. */
    statemachined_link_v1_CancelReason reason;
} statemachined_link_v1_Cancel;

typedef struct _statemachined_link_v1_Ping {
    char dummy_field;
} statemachined_link_v1_Ping;

typedef struct _statemachined_link_v1_StateRequest {
    char dummy_field;
} statemachined_link_v1_StateRequest;

typedef struct _statemachined_link_v1_Wiring {
    bool has_invert;
    uint32_t invert;
    bool has_enable;
    uint32_t enable;
    bool has_safe;
    uint32_t safe;
    /* Per input line, index = line. Empty leaves the table alone; anything else
 replaces all of it, and the lines it does not name get 0. */
    pb_size_t debounce_ms_count;
    uint32_t debounce_ms[32];
} statemachined_link_v1_Wiring;

typedef struct _statemachined_link_v1_Timers {
    uint32_t enable;
} statemachined_link_v1_Timers;

typedef struct _statemachined_link_v1_Pins {
    statemachined_link_v1_Direction dir;
} statemachined_link_v1_Pins;

typedef struct _statemachined_link_v1_Autorun {
    /* Absent makes this a question: nothing changes, and the settings are
 reported. */
    bool has_enabled;
    bool enabled;
    bool has_graph_index;
    uint32_t graph_index;
    bool has_cap_ms;
    int32_t cap_ms;
    bool has_seed;
    uint64_t seed;
    bool has_first_trial_id;
    uint32_t first_trial_id;
    /* Absent means true. */
    bool has_start_now;
    bool start_now;
} statemachined_link_v1_Autorun;

typedef struct _statemachined_link_v1_Save {
    char dummy_field;
} statemachined_link_v1_Save;

/* Everything the daemon sends is one of these. */
typedef struct _statemachined_link_v1_HostMessage {
    /* The sender's per-direction counter, an unsigned 16-bit value that wraps.
 It identifies one message so a resend of it can be recognised; it orders
 nothing. See `docs/reference/protocol.md` §1.2. */
    uint16_t message_id;
    pb_size_t which_body;
    union {
        statemachined_link_v1_Hello hello;
        statemachined_link_v1_SetBegin set_begin;
        statemachined_link_v1_SetEnd set_end;
        statemachined_link_v1_GraphBegin graph_begin;
        statemachined_link_v1_GraphDist graph_dist;
        statemachined_link_v1_GraphState graph_state;
        statemachined_link_v1_GraphTransition graph_transition;
        statemachined_link_v1_GraphAction graph_action;
        statemachined_link_v1_GraphTimer graph_timer;
        statemachined_link_v1_GraphEnd graph_end;
        statemachined_link_v1_Configure configure;
        statemachined_link_v1_Start start;
        statemachined_link_v1_Cancel cancel;
        statemachined_link_v1_Ping ping;
        statemachined_link_v1_StateRequest state;
        statemachined_link_v1_Wiring wiring;
        statemachined_link_v1_Timers timers;
        statemachined_link_v1_Pins pins;
        statemachined_link_v1_Autorun autorun;
        statemachined_link_v1_Save save;
    } body;
} statemachined_link_v1_HostMessage;

typedef struct _statemachined_link_v1_Caps {
    /* The longest frame the board accepts, in encoded bytes including the
 delimiter. */
    uint32_t max_frame;
    uint32_t max_states;
    uint32_t max_transitions;
    uint32_t max_output_actions;
    uint32_t max_distributions;
    uint32_t max_choice_options;
    uint32_t max_path;
    uint32_t max_graphs;
    uint32_t max_timers;
    uint32_t first_timer_line;
} statemachined_link_v1_Caps;

typedef struct _statemachined_link_v1_HelloAck {
    uint32_t proto;
    char board[24];
    char fw[48];
    uint32_t n_input_lines;
    uint32_t n_output_lines;
    uint32_t scan_hz;
    bool has_caps;
    statemachined_link_v1_Caps caps;
    bool has_set;
    uint32_t set_version;
    uint32_t n_graphs;
    bool has_wiring;
} statemachined_link_v1_HelloAck;

typedef struct _statemachined_link_v1_Ack {
    /* A reply to `timers` only: the mask the device now holds, and how many
 timers the committed set declares. */
    bool has_enable;
    uint32_t enable;
    bool has_n_timers;
    uint32_t n_timers;
} statemachined_link_v1_Ack;

typedef struct _statemachined_link_v1_SetOk {
    uint32_t set_version;
    uint32_t n_graphs;
    uint32_t n_states;
    uint32_t n_transitions;
    uint32_t n_output_actions;
} statemachined_link_v1_SetOk;

typedef struct _statemachined_link_v1_Armed {
    uint32_t trial_id;
    uint32_t set_version;
    uint32_t graph_index;
} statemachined_link_v1_Armed;

typedef struct _statemachined_link_v1_Started {
    uint32_t trial_id;
    uint32_t at_us;
    /* `serial` or `line`. */
    statemachined_link_v1_StartSource by;
    /* The line, when `by` is `line`. */
    bool has_line;
    uint32_t line;
} statemachined_link_v1_Started;

typedef struct _statemachined_link_v1_CancelAck {
    uint32_t trial_id;
    bool cancelled;
    int32_t outcome;
} statemachined_link_v1_CancelAck;

/* One completed state visit: a `result_path` row, and a `visit`'s `v`. */
typedef struct _statemachined_link_v1_StateVisit {
    /* Within the graph. */
    uint32_t state;
    statemachined_link_v1_ExitCause exit;
    /* Which of this state's transitions fired, or 255 for an exit that was not
 one. */
    uint32_t transition;
    /* The realised draw, in ms. */
    int32_t drawn_ms;
    /* Device clock. */
    uint32_t entered_us;
    uint32_t duration_us;
} statemachined_link_v1_StateVisit;

typedef struct _statemachined_link_v1_ResultBegin {
    uint32_t trial_id;
    int32_t outcome;
    uint32_t cancel_reason;
    uint32_t total_us;
    uint32_t path_len;
    uint32_t first_seq;
    uint32_t total_visits;
    bool truncated;
} statemachined_link_v1_ResultBegin;

typedef struct _statemachined_link_v1_ResultPath {
    uint32_t trial_id;
    uint32_t from;
    pb_size_t p_count;
    statemachined_link_v1_StateVisit p[14];
} statemachined_link_v1_ResultPath;

typedef struct _statemachined_link_v1_ResultEnd {
    uint32_t trial_id;
    /* CRC-16/CCITT-FALSE over the protobuf bytes of `result_begin` and every
 `result_path`, in order. */
    uint32_t checksum;
} statemachined_link_v1_ResultEnd;

typedef struct _statemachined_link_v1_Event {
    uint32_t us;
    uint32_t word;
} statemachined_link_v1_Event;

typedef struct _statemachined_link_v1_Error {
    char code[24];
    char message[80];
    char context[64];
} statemachined_link_v1_Error;

typedef struct _statemachined_link_v1_Log {
    char level[8];
    char message[96];
} statemachined_link_v1_Log;

typedef struct _statemachined_link_v1_Pong {
    uint32_t up_us;
    uint32_t us;
} statemachined_link_v1_Pong;

typedef struct _statemachined_link_v1_GraphReport {
    bool has_set;
    uint32_t set_version;
    uint32_t n_graphs;
    uint32_t index;
} statemachined_link_v1_GraphReport;

typedef struct _statemachined_link_v1_IoReport {
    uint32_t in;
    uint32_t out;
} statemachined_link_v1_IoReport;

typedef struct _statemachined_link_v1_ScanReport {
    uint32_t hz;
    uint32_t overruns;
    uint32_t worst_gap;
    uint32_t tx_stalls;
    uint32_t visits_dropped;
    uint32_t timers_enabled;
    uint32_t timers_running;
} statemachined_link_v1_ScanReport;

typedef struct _statemachined_link_v1_StateReport {
    uint32_t link_state;
    bool has_graph;
    statemachined_link_v1_GraphReport graph;
    bool has_wiring;
    bool autorun;
    uint32_t trial_id;
    bool running;
    uint32_t current_state;
    uint32_t up_us;
    /* Frames the board threw away whole: too long, not COBS, or a CRC that did
 not match. */
    uint32_t dropped_lines;
    /* Frames that arrived intact and still could not be read as a message. */
    uint32_t bad_lines;
    bool has_io;
    statemachined_link_v1_IoReport io;
    bool has_scan;
    statemachined_link_v1_ScanReport scan;
} statemachined_link_v1_StateReport;

typedef struct _statemachined_link_v1_Visit {
    uint32_t trial_id;
    uint32_t seq;
    bool has_v;
    statemachined_link_v1_StateVisit v;
} statemachined_link_v1_Visit;

typedef struct _statemachined_link_v1_PinMap {
    statemachined_link_v1_Direction dir;
    uint32_t n;
    pb_size_t pins_count;
    char pins[32][8];
} statemachined_link_v1_PinMap;

typedef struct _statemachined_link_v1_AutorunOk {
    bool enabled;
    bool active;
    uint32_t graph_index;
    int32_t cap_ms;
    uint32_t next_trial_id;
} statemachined_link_v1_AutorunOk;

typedef struct _statemachined_link_v1_Saved {
    bool has_set;
    uint32_t set_version;
    bool autorun;
    uint32_t write_count;
    bool written;
} statemachined_link_v1_Saved;

/* Everything the board sends is one of these. */
typedef struct _statemachined_link_v1_DeviceMessage {
    uint16_t message_id;
    /* The `message_id` of the command this answers. Absent on everything the
 board sends unasked — `visit`, the result, a line-started `started` — and
 on a refusal of a frame that could not be read. */
    bool has_in_reply_to;
    uint16_t in_reply_to;
    pb_size_t which_body;
    union {
        statemachined_link_v1_HelloAck hello_ack;
        statemachined_link_v1_Ack ack;
        statemachined_link_v1_SetOk set_ok;
        statemachined_link_v1_Armed armed;
        statemachined_link_v1_Started started;
        statemachined_link_v1_CancelAck cancel_ack;
        statemachined_link_v1_ResultBegin result_begin;
        statemachined_link_v1_ResultPath result_path;
        statemachined_link_v1_ResultEnd result_end;
        statemachined_link_v1_Event event;
        statemachined_link_v1_Error error;
        statemachined_link_v1_Log log;
        statemachined_link_v1_Pong pong;
        statemachined_link_v1_StateReport state_report;
        statemachined_link_v1_Visit visit;
        statemachined_link_v1_PinMap pin_map;
        statemachined_link_v1_AutorunOk autorun_ok;
        statemachined_link_v1_Saved saved;
    } body;
} statemachined_link_v1_DeviceMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _statemachined_link_v1_DistKind_MIN statemachined_link_v1_DistKind_DIST_KIND_UNSPECIFIED
#define _statemachined_link_v1_DistKind_MAX statemachined_link_v1_DistKind_DIST_KIND_CHOICE
#define _statemachined_link_v1_DistKind_ARRAYSIZE ((statemachined_link_v1_DistKind)(statemachined_link_v1_DistKind_DIST_KIND_CHOICE+1))

#define _statemachined_link_v1_ActionOn_MIN statemachined_link_v1_ActionOn_ACTION_ON_UNSPECIFIED
#define _statemachined_link_v1_ActionOn_MAX statemachined_link_v1_ActionOn_ACTION_ON_EXIT
#define _statemachined_link_v1_ActionOn_ARRAYSIZE ((statemachined_link_v1_ActionOn)(statemachined_link_v1_ActionOn_ACTION_ON_EXIT+1))

#define _statemachined_link_v1_ActionKind_MIN statemachined_link_v1_ActionKind_ACTION_KIND_UNSPECIFIED
#define _statemachined_link_v1_ActionKind_MAX statemachined_link_v1_ActionKind_ACTION_KIND_TIMER_CANCEL
#define _statemachined_link_v1_ActionKind_ARRAYSIZE ((statemachined_link_v1_ActionKind)(statemachined_link_v1_ActionKind_ACTION_KIND_TIMER_CANCEL+1))

#define _statemachined_link_v1_StartSource_MIN statemachined_link_v1_StartSource_START_SOURCE_UNSPECIFIED
#define _statemachined_link_v1_StartSource_MAX statemachined_link_v1_StartSource_START_SOURCE_BOTH
#define _statemachined_link_v1_StartSource_ARRAYSIZE ((statemachined_link_v1_StartSource)(statemachined_link_v1_StartSource_START_SOURCE_BOTH+1))

#define _statemachined_link_v1_CancelReason_MIN statemachined_link_v1_CancelReason_CANCEL_REASON_UNSPECIFIED
#define _statemachined_link_v1_CancelReason_MAX statemachined_link_v1_CancelReason_CANCEL_REASON_TRIAL_TIMEOUT
#define _statemachined_link_v1_CancelReason_ARRAYSIZE ((statemachined_link_v1_CancelReason)(statemachined_link_v1_CancelReason_CANCEL_REASON_TRIAL_TIMEOUT+1))

#define _statemachined_link_v1_Direction_MIN statemachined_link_v1_Direction_DIRECTION_UNSPECIFIED
#define _statemachined_link_v1_Direction_MAX statemachined_link_v1_Direction_DIRECTION_OUT
#define _statemachined_link_v1_Direction_ARRAYSIZE ((statemachined_link_v1_Direction)(statemachined_link_v1_Direction_DIRECTION_OUT+1))

#define _statemachined_link_v1_ExitCause_MIN statemachined_link_v1_ExitCause_EXIT_CAUSE_UNSPECIFIED
#define _statemachined_link_v1_ExitCause_MAX statemachined_link_v1_ExitCause_EXIT_CAUSE_TERMINAL
#define _statemachined_link_v1_ExitCause_ARRAYSIZE ((statemachined_link_v1_ExitCause)(statemachined_link_v1_ExitCause_EXIT_CAUSE_TERMINAL+1))







#define statemachined_link_v1_GraphDist_kind_ENUMTYPE statemachined_link_v1_DistKind




#define statemachined_link_v1_GraphAction_on_ENUMTYPE statemachined_link_v1_ActionOn
#define statemachined_link_v1_GraphAction_kind_ENUMTYPE statemachined_link_v1_ActionKind




#define statemachined_link_v1_Configure_start_ENUMTYPE statemachined_link_v1_StartSource


#define statemachined_link_v1_Cancel_reason_ENUMTYPE statemachined_link_v1_CancelReason





#define statemachined_link_v1_Pins_dir_ENUMTYPE statemachined_link_v1_Direction








#define statemachined_link_v1_Started_by_ENUMTYPE statemachined_link_v1_StartSource


#define statemachined_link_v1_StateVisit_exit_ENUMTYPE statemachined_link_v1_ExitCause













#define statemachined_link_v1_PinMap_dir_ENUMTYPE statemachined_link_v1_Direction




/* Initializer values for message structs */
#define statemachined_link_v1_HostMessage_init_default {0, 0, {statemachined_link_v1_Hello_init_default}}
#define statemachined_link_v1_DeviceMessage_init_default {0, false, 0, 0, {statemachined_link_v1_HelloAck_init_default}}
#define statemachined_link_v1_Hello_init_default {0, 0}
#define statemachined_link_v1_SetBegin_init_default {0, 0}
#define statemachined_link_v1_SetEnd_init_default {0, 0, 0, 0}
#define statemachined_link_v1_GraphBegin_init_default {0, 0, 0}
#define statemachined_link_v1_GraphDist_init_default {0, _statemachined_link_v1_DistKind_MIN, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define statemachined_link_v1_Timeout_init_default {0, 0}
#define statemachined_link_v1_GraphState_init_default {0, false, 0, false, statemachined_link_v1_Timeout_init_default, false, 0}
#define statemachined_link_v1_GraphTransition_init_default {0, 0, 0, 0, false, 0, 0}
#define statemachined_link_v1_GraphAction_init_default {_statemachined_link_v1_ActionOn_MIN, 0, _statemachined_link_v1_ActionKind_MIN, 0, 0}
#define statemachined_link_v1_GraphTimer_init_default {0, 0, false, 0, false, 0, false, 0, false, 0, 0, 0, 0, 0, 0}
#define statemachined_link_v1_GraphEnd_init_default {0, 0}
#define statemachined_link_v1_Patch_init_default {0, false, 0, false, 0, false, 0}
#define statemachined_link_v1_Configure_init_default {0, 0, 0, 0, _statemachined_link_v1_StartSource_MIN, false, 0, false, 0, 0, {statemachined_link_v1_Patch_init_default, statemachined_link_v1_Patch_init_default, statemachined_link_v1_Patch_init_default, statemachined_link_v1_Patch_init_default, statemachined_link_v1_Patch_init_default, statemachined_link_v1_Patch_init_default, statemachined_link_v1_Patch_init_default, statemachined_link_v1_Patch_init_default}}
#define statemachined_link_v1_Start_init_default {0}
#define statemachined_link_v1_Cancel_init_default {0, _statemachined_link_v1_CancelReason_MIN}
#define statemachined_link_v1_Ping_init_default  {0}
#define statemachined_link_v1_StateRequest_init_default {0}
#define statemachined_link_v1_Wiring_init_default {false, 0, false, 0, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define statemachined_link_v1_Timers_init_default {0}
#define statemachined_link_v1_Pins_init_default  {_statemachined_link_v1_Direction_MIN}
#define statemachined_link_v1_Autorun_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define statemachined_link_v1_Save_init_default  {0}
#define statemachined_link_v1_Caps_init_default  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define statemachined_link_v1_HelloAck_init_default {0, "", "", 0, 0, 0, false, statemachined_link_v1_Caps_init_default, 0, 0, 0, 0}
#define statemachined_link_v1_Ack_init_default   {false, 0, false, 0}
#define statemachined_link_v1_SetOk_init_default {0, 0, 0, 0, 0}
#define statemachined_link_v1_Armed_init_default {0, 0, 0}
#define statemachined_link_v1_Started_init_default {0, 0, _statemachined_link_v1_StartSource_MIN, false, 0}
#define statemachined_link_v1_CancelAck_init_default {0, 0, 0}
#define statemachined_link_v1_StateVisit_init_default {0, _statemachined_link_v1_ExitCause_MIN, 0, 0, 0, 0}
#define statemachined_link_v1_ResultBegin_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define statemachined_link_v1_ResultPath_init_default {0, 0, 0, {statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default, statemachined_link_v1_StateVisit_init_default}}
#define statemachined_link_v1_ResultEnd_init_default {0, 0}
#define statemachined_link_v1_Event_init_default {0, 0}
#define statemachined_link_v1_Error_init_default {"", "", ""}
#define statemachined_link_v1_Log_init_default   {"", ""}
#define statemachined_link_v1_Pong_init_default  {0, 0}
#define statemachined_link_v1_GraphReport_init_default {0, 0, 0, 0}
#define statemachined_link_v1_IoReport_init_default {0, 0}
#define statemachined_link_v1_ScanReport_init_default {0, 0, 0, 0, 0, 0, 0}
#define statemachined_link_v1_StateReport_init_default {0, false, statemachined_link_v1_GraphReport_init_default, 0, 0, 0, 0, 0, 0, 0, 0, false, statemachined_link_v1_IoReport_init_default, false, statemachined_link_v1_ScanReport_init_default}
#define statemachined_link_v1_Visit_init_default {0, 0, false, statemachined_link_v1_StateVisit_init_default}
#define statemachined_link_v1_PinMap_init_default {_statemachined_link_v1_Direction_MIN, 0, 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define statemachined_link_v1_AutorunOk_init_default {0, 0, 0, 0, 0}
#define statemachined_link_v1_Saved_init_default {0, 0, 0, 0, 0}
#define statemachined_link_v1_HostMessage_init_zero {0, 0, {statemachined_link_v1_Hello_init_zero}}
#define statemachined_link_v1_DeviceMessage_init_zero {0, false, 0, 0, {statemachined_link_v1_HelloAck_init_zero}}
#define statemachined_link_v1_Hello_init_zero    {0, 0}
#define statemachined_link_v1_SetBegin_init_zero {0, 0}
#define statemachined_link_v1_SetEnd_init_zero   {0, 0, 0, 0}
#define statemachined_link_v1_GraphBegin_init_zero {0, 0, 0}
#define statemachined_link_v1_GraphDist_init_zero {0, _statemachined_link_v1_DistKind_MIN, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define statemachined_link_v1_Timeout_init_zero  {0, 0}
#define statemachined_link_v1_GraphState_init_zero {0, false, 0, false, statemachined_link_v1_Timeout_init_zero, false, 0}
#define statemachined_link_v1_GraphTransition_init_zero {0, 0, 0, 0, false, 0, 0}
#define statemachined_link_v1_GraphAction_init_zero {_statemachined_link_v1_ActionOn_MIN, 0, _statemachined_link_v1_ActionKind_MIN, 0, 0}
#define statemachined_link_v1_GraphTimer_init_zero {0, 0, false, 0, false, 0, false, 0, false, 0, 0, 0, 0, 0, 0}
#define statemachined_link_v1_GraphEnd_init_zero {0, 0}
#define statemachined_link_v1_Patch_init_zero    {0, false, 0, false, 0, false, 0}
#define statemachined_link_v1_Configure_init_zero {0, 0, 0, 0, _statemachined_link_v1_StartSource_MIN, false, 0, false, 0, 0, {statemachined_link_v1_Patch_init_zero, statemachined_link_v1_Patch_init_zero, statemachined_link_v1_Patch_init_zero, statemachined_link_v1_Patch_init_zero, statemachined_link_v1_Patch_init_zero, statemachined_link_v1_Patch_init_zero, statemachined_link_v1_Patch_init_zero, statemachined_link_v1_Patch_init_zero}}
#define statemachined_link_v1_Start_init_zero    {0}
#define statemachined_link_v1_Cancel_init_zero   {0, _statemachined_link_v1_CancelReason_MIN}
#define statemachined_link_v1_Ping_init_zero     {0}
#define statemachined_link_v1_StateRequest_init_zero {0}
#define statemachined_link_v1_Wiring_init_zero   {false, 0, false, 0, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define statemachined_link_v1_Timers_init_zero   {0}
#define statemachined_link_v1_Pins_init_zero     {_statemachined_link_v1_Direction_MIN}
#define statemachined_link_v1_Autorun_init_zero  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define statemachined_link_v1_Save_init_zero     {0}
#define statemachined_link_v1_Caps_init_zero     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define statemachined_link_v1_HelloAck_init_zero {0, "", "", 0, 0, 0, false, statemachined_link_v1_Caps_init_zero, 0, 0, 0, 0}
#define statemachined_link_v1_Ack_init_zero      {false, 0, false, 0}
#define statemachined_link_v1_SetOk_init_zero    {0, 0, 0, 0, 0}
#define statemachined_link_v1_Armed_init_zero    {0, 0, 0}
#define statemachined_link_v1_Started_init_zero  {0, 0, _statemachined_link_v1_StartSource_MIN, false, 0}
#define statemachined_link_v1_CancelAck_init_zero {0, 0, 0}
#define statemachined_link_v1_StateVisit_init_zero {0, _statemachined_link_v1_ExitCause_MIN, 0, 0, 0, 0}
#define statemachined_link_v1_ResultBegin_init_zero {0, 0, 0, 0, 0, 0, 0, 0}
#define statemachined_link_v1_ResultPath_init_zero {0, 0, 0, {statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero, statemachined_link_v1_StateVisit_init_zero}}
#define statemachined_link_v1_ResultEnd_init_zero {0, 0}
#define statemachined_link_v1_Event_init_zero    {0, 0}
#define statemachined_link_v1_Error_init_zero    {"", "", ""}
#define statemachined_link_v1_Log_init_zero      {"", ""}
#define statemachined_link_v1_Pong_init_zero     {0, 0}
#define statemachined_link_v1_GraphReport_init_zero {0, 0, 0, 0}
#define statemachined_link_v1_IoReport_init_zero {0, 0}
#define statemachined_link_v1_ScanReport_init_zero {0, 0, 0, 0, 0, 0, 0}
#define statemachined_link_v1_StateReport_init_zero {0, false, statemachined_link_v1_GraphReport_init_zero, 0, 0, 0, 0, 0, 0, 0, 0, false, statemachined_link_v1_IoReport_init_zero, false, statemachined_link_v1_ScanReport_init_zero}
#define statemachined_link_v1_Visit_init_zero    {0, 0, false, statemachined_link_v1_StateVisit_init_zero}
#define statemachined_link_v1_PinMap_init_zero   {_statemachined_link_v1_Direction_MIN, 0, 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define statemachined_link_v1_AutorunOk_init_zero {0, 0, 0, 0, 0}
#define statemachined_link_v1_Saved_init_zero    {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define statemachined_link_v1_Hello_proto_tag    1
#define statemachined_link_v1_Hello_seed_tag     2
#define statemachined_link_v1_SetBegin_set_version_tag 1
#define statemachined_link_v1_SetBegin_n_graphs_tag 2
#define statemachined_link_v1_SetEnd_n_states_tag 1
#define statemachined_link_v1_SetEnd_n_transitions_tag 2
#define statemachined_link_v1_SetEnd_n_output_actions_tag 3
#define statemachined_link_v1_SetEnd_checksum_tag 4
#define statemachined_link_v1_GraphBegin_slot_tag 1
#define statemachined_link_v1_GraphBegin_n_states_tag 2
#define statemachined_link_v1_GraphBegin_entry_tag 3
#define statemachined_link_v1_GraphDist_i_tag    1
#define statemachined_link_v1_GraphDist_kind_tag 2
#define statemachined_link_v1_GraphDist_a_tag    3
#define statemachined_link_v1_GraphDist_b_tag    4
#define statemachined_link_v1_GraphDist_c_tag    5
#define statemachined_link_v1_GraphDist_opts_tag 6
#define statemachined_link_v1_GraphDist_weights_tag 7
#define statemachined_link_v1_Timeout_dist_tag   1
#define statemachined_link_v1_Timeout_target_tag 2
#define statemachined_link_v1_GraphState_i_tag   1
#define statemachined_link_v1_GraphState_terminal_tag 2
#define statemachined_link_v1_GraphState_timeout_tag 3
#define statemachined_link_v1_GraphState_relight_tag 4
#define statemachined_link_v1_GraphTransition_all_tag 1
#define statemachined_link_v1_GraphTransition_any_tag 2
#define statemachined_link_v1_GraphTransition_none_tag 3
#define statemachined_link_v1_GraphTransition_target_tag 4
#define statemachined_link_v1_GraphTransition_hold_tag 5
#define statemachined_link_v1_GraphTransition_level_tag 6
#define statemachined_link_v1_GraphAction_on_tag 1
#define statemachined_link_v1_GraphAction_line_tag 2
#define statemachined_link_v1_GraphAction_kind_tag 3
#define statemachined_link_v1_GraphAction_ms_tag 4
#define statemachined_link_v1_GraphAction_timer_tag 5
#define statemachined_link_v1_GraphTimer_i_tag   1
#define statemachined_link_v1_GraphTimer_width_tag 2
#define statemachined_link_v1_GraphTimer_delay_tag 3
#define statemachined_link_v1_GraphTimer_gap_tag 4
#define statemachined_link_v1_GraphTimer_line_tag 5
#define statemachined_link_v1_GraphTimer_loops_tag 6
#define statemachined_link_v1_GraphTimer_all_tag 7
#define statemachined_link_v1_GraphTimer_any_tag 8
#define statemachined_link_v1_GraphTimer_none_tag 9
#define statemachined_link_v1_GraphTimer_active_low_tag 10
#define statemachined_link_v1_GraphTimer_trial_bound_tag 11
#define statemachined_link_v1_GraphEnd_n_transitions_tag 1
#define statemachined_link_v1_GraphEnd_n_output_actions_tag 2
#define statemachined_link_v1_Patch_i_tag        1
#define statemachined_link_v1_Patch_a_tag        2
#define statemachined_link_v1_Patch_b_tag        3
#define statemachined_link_v1_Patch_c_tag        4
#define statemachined_link_v1_Configure_trial_id_tag 1
#define statemachined_link_v1_Configure_set_version_tag 2
#define statemachined_link_v1_Configure_graph_index_tag 3
#define statemachined_link_v1_Configure_cap_ms_tag 4
#define statemachined_link_v1_Configure_start_tag 5
#define statemachined_link_v1_Configure_start_line_tag 6
#define statemachined_link_v1_Configure_timers_tag 7
#define statemachined_link_v1_Configure_patch_tag 8
#define statemachined_link_v1_Start_trial_id_tag 1
#define statemachined_link_v1_Cancel_trial_id_tag 1
#define statemachined_link_v1_Cancel_reason_tag  2
#define statemachined_link_v1_Wiring_invert_tag  1
#define statemachined_link_v1_Wiring_enable_tag  2
#define statemachined_link_v1_Wiring_safe_tag    3
#define statemachined_link_v1_Wiring_debounce_ms_tag 4
#define statemachined_link_v1_Timers_enable_tag  1
#define statemachined_link_v1_Pins_dir_tag       1
#define statemachined_link_v1_Autorun_enabled_tag 1
#define statemachined_link_v1_Autorun_graph_index_tag 2
#define statemachined_link_v1_Autorun_cap_ms_tag 3
#define statemachined_link_v1_Autorun_seed_tag   4
#define statemachined_link_v1_Autorun_first_trial_id_tag 5
#define statemachined_link_v1_Autorun_start_now_tag 6
#define statemachined_link_v1_HostMessage_message_id_tag 1
#define statemachined_link_v1_HostMessage_hello_tag 10
#define statemachined_link_v1_HostMessage_set_begin_tag 11
#define statemachined_link_v1_HostMessage_set_end_tag 12
#define statemachined_link_v1_HostMessage_graph_begin_tag 13
#define statemachined_link_v1_HostMessage_graph_dist_tag 14
#define statemachined_link_v1_HostMessage_graph_state_tag 15
#define statemachined_link_v1_HostMessage_graph_transition_tag 16
#define statemachined_link_v1_HostMessage_graph_action_tag 17
#define statemachined_link_v1_HostMessage_graph_timer_tag 18
#define statemachined_link_v1_HostMessage_graph_end_tag 19
#define statemachined_link_v1_HostMessage_configure_tag 20
#define statemachined_link_v1_HostMessage_start_tag 21
#define statemachined_link_v1_HostMessage_cancel_tag 22
#define statemachined_link_v1_HostMessage_ping_tag 23
#define statemachined_link_v1_HostMessage_state_tag 24
#define statemachined_link_v1_HostMessage_wiring_tag 25
#define statemachined_link_v1_HostMessage_timers_tag 26
#define statemachined_link_v1_HostMessage_pins_tag 27
#define statemachined_link_v1_HostMessage_autorun_tag 28
#define statemachined_link_v1_HostMessage_save_tag 29
#define statemachined_link_v1_Caps_max_frame_tag 1
#define statemachined_link_v1_Caps_max_states_tag 2
#define statemachined_link_v1_Caps_max_transitions_tag 3
#define statemachined_link_v1_Caps_max_output_actions_tag 4
#define statemachined_link_v1_Caps_max_distributions_tag 5
#define statemachined_link_v1_Caps_max_choice_options_tag 6
#define statemachined_link_v1_Caps_max_path_tag  7
#define statemachined_link_v1_Caps_max_graphs_tag 8
#define statemachined_link_v1_Caps_max_timers_tag 9
#define statemachined_link_v1_Caps_first_timer_line_tag 10
#define statemachined_link_v1_HelloAck_proto_tag 1
#define statemachined_link_v1_HelloAck_board_tag 2
#define statemachined_link_v1_HelloAck_fw_tag    3
#define statemachined_link_v1_HelloAck_n_input_lines_tag 4
#define statemachined_link_v1_HelloAck_n_output_lines_tag 5
#define statemachined_link_v1_HelloAck_scan_hz_tag 6
#define statemachined_link_v1_HelloAck_caps_tag  7
#define statemachined_link_v1_HelloAck_has_set_tag 8
#define statemachined_link_v1_HelloAck_set_version_tag 9
#define statemachined_link_v1_HelloAck_n_graphs_tag 10
#define statemachined_link_v1_HelloAck_has_wiring_tag 11
#define statemachined_link_v1_Ack_enable_tag     1
#define statemachined_link_v1_Ack_n_timers_tag   2
#define statemachined_link_v1_SetOk_set_version_tag 1
#define statemachined_link_v1_SetOk_n_graphs_tag 2
#define statemachined_link_v1_SetOk_n_states_tag 3
#define statemachined_link_v1_SetOk_n_transitions_tag 4
#define statemachined_link_v1_SetOk_n_output_actions_tag 5
#define statemachined_link_v1_Armed_trial_id_tag 1
#define statemachined_link_v1_Armed_set_version_tag 2
#define statemachined_link_v1_Armed_graph_index_tag 3
#define statemachined_link_v1_Started_trial_id_tag 1
#define statemachined_link_v1_Started_at_us_tag  2
#define statemachined_link_v1_Started_by_tag     3
#define statemachined_link_v1_Started_line_tag   4
#define statemachined_link_v1_CancelAck_trial_id_tag 1
#define statemachined_link_v1_CancelAck_cancelled_tag 2
#define statemachined_link_v1_CancelAck_outcome_tag 3
#define statemachined_link_v1_StateVisit_state_tag 1
#define statemachined_link_v1_StateVisit_exit_tag 2
#define statemachined_link_v1_StateVisit_transition_tag 3
#define statemachined_link_v1_StateVisit_drawn_ms_tag 4
#define statemachined_link_v1_StateVisit_entered_us_tag 5
#define statemachined_link_v1_StateVisit_duration_us_tag 6
#define statemachined_link_v1_ResultBegin_trial_id_tag 1
#define statemachined_link_v1_ResultBegin_outcome_tag 2
#define statemachined_link_v1_ResultBegin_cancel_reason_tag 3
#define statemachined_link_v1_ResultBegin_total_us_tag 4
#define statemachined_link_v1_ResultBegin_path_len_tag 5
#define statemachined_link_v1_ResultBegin_first_seq_tag 6
#define statemachined_link_v1_ResultBegin_total_visits_tag 7
#define statemachined_link_v1_ResultBegin_truncated_tag 8
#define statemachined_link_v1_ResultPath_trial_id_tag 1
#define statemachined_link_v1_ResultPath_from_tag 2
#define statemachined_link_v1_ResultPath_p_tag   3
#define statemachined_link_v1_ResultEnd_trial_id_tag 1
#define statemachined_link_v1_ResultEnd_checksum_tag 2
#define statemachined_link_v1_Event_us_tag       1
#define statemachined_link_v1_Event_word_tag     2
#define statemachined_link_v1_Error_code_tag     1
#define statemachined_link_v1_Error_message_tag  2
#define statemachined_link_v1_Error_context_tag  3
#define statemachined_link_v1_Log_level_tag      1
#define statemachined_link_v1_Log_message_tag    2
#define statemachined_link_v1_Pong_up_us_tag     1
#define statemachined_link_v1_Pong_us_tag        2
#define statemachined_link_v1_GraphReport_has_set_tag 1
#define statemachined_link_v1_GraphReport_set_version_tag 2
#define statemachined_link_v1_GraphReport_n_graphs_tag 3
#define statemachined_link_v1_GraphReport_index_tag 4
#define statemachined_link_v1_IoReport_in_tag    1
#define statemachined_link_v1_IoReport_out_tag   2
#define statemachined_link_v1_ScanReport_hz_tag  1
#define statemachined_link_v1_ScanReport_overruns_tag 2
#define statemachined_link_v1_ScanReport_worst_gap_tag 3
#define statemachined_link_v1_ScanReport_tx_stalls_tag 4
#define statemachined_link_v1_ScanReport_visits_dropped_tag 5
#define statemachined_link_v1_ScanReport_timers_enabled_tag 6
#define statemachined_link_v1_ScanReport_timers_running_tag 7
#define statemachined_link_v1_StateReport_link_state_tag 1
#define statemachined_link_v1_StateReport_graph_tag 2
#define statemachined_link_v1_StateReport_has_wiring_tag 3
#define statemachined_link_v1_StateReport_autorun_tag 4
#define statemachined_link_v1_StateReport_trial_id_tag 5
#define statemachined_link_v1_StateReport_running_tag 6
#define statemachined_link_v1_StateReport_current_state_tag 7
#define statemachined_link_v1_StateReport_up_us_tag 8
#define statemachined_link_v1_StateReport_dropped_lines_tag 9
#define statemachined_link_v1_StateReport_bad_lines_tag 10
#define statemachined_link_v1_StateReport_io_tag 11
#define statemachined_link_v1_StateReport_scan_tag 12
#define statemachined_link_v1_Visit_trial_id_tag 1
#define statemachined_link_v1_Visit_seq_tag      2
#define statemachined_link_v1_Visit_v_tag        3
#define statemachined_link_v1_PinMap_dir_tag     1
#define statemachined_link_v1_PinMap_n_tag       2
#define statemachined_link_v1_PinMap_pins_tag    3
#define statemachined_link_v1_AutorunOk_enabled_tag 1
#define statemachined_link_v1_AutorunOk_active_tag 2
#define statemachined_link_v1_AutorunOk_graph_index_tag 3
#define statemachined_link_v1_AutorunOk_cap_ms_tag 4
#define statemachined_link_v1_AutorunOk_next_trial_id_tag 5
#define statemachined_link_v1_Saved_has_set_tag  1
#define statemachined_link_v1_Saved_set_version_tag 2
#define statemachined_link_v1_Saved_autorun_tag  3
#define statemachined_link_v1_Saved_write_count_tag 4
#define statemachined_link_v1_Saved_written_tag  5
#define statemachined_link_v1_DeviceMessage_message_id_tag 1
#define statemachined_link_v1_DeviceMessage_in_reply_to_tag 2
#define statemachined_link_v1_DeviceMessage_hello_ack_tag 10
#define statemachined_link_v1_DeviceMessage_ack_tag 11
#define statemachined_link_v1_DeviceMessage_set_ok_tag 12
#define statemachined_link_v1_DeviceMessage_armed_tag 13
#define statemachined_link_v1_DeviceMessage_started_tag 14
#define statemachined_link_v1_DeviceMessage_cancel_ack_tag 15
#define statemachined_link_v1_DeviceMessage_result_begin_tag 16
#define statemachined_link_v1_DeviceMessage_result_path_tag 17
#define statemachined_link_v1_DeviceMessage_result_end_tag 18
#define statemachined_link_v1_DeviceMessage_event_tag 19
#define statemachined_link_v1_DeviceMessage_error_tag 20
#define statemachined_link_v1_DeviceMessage_log_tag 21
#define statemachined_link_v1_DeviceMessage_pong_tag 22
#define statemachined_link_v1_DeviceMessage_state_report_tag 23
#define statemachined_link_v1_DeviceMessage_visit_tag 24
#define statemachined_link_v1_DeviceMessage_pin_map_tag 25
#define statemachined_link_v1_DeviceMessage_autorun_ok_tag 26
#define statemachined_link_v1_DeviceMessage_saved_tag 27

/* Struct field encoding specification for nanopb */
#define statemachined_link_v1_HostMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   message_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,hello,body.hello),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,set_begin,body.set_begin),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,set_end,body.set_end),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,graph_begin,body.graph_begin),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,graph_dist,body.graph_dist),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,graph_state,body.graph_state),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,graph_transition,body.graph_transition),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,graph_action,body.graph_action),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,graph_timer,body.graph_timer),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,graph_end,body.graph_end),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,configure,body.configure),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,start,body.start),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,cancel,body.cancel),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ping,body.ping),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,state,body.state),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,wiring,body.wiring),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,timers,body.timers),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,pins,body.pins),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,autorun,body.autorun),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,save,body.save),  29)
#define statemachined_link_v1_HostMessage_CALLBACK NULL
#define statemachined_link_v1_HostMessage_DEFAULT NULL
#define statemachined_link_v1_HostMessage_body_hello_MSGTYPE statemachined_link_v1_Hello
#define statemachined_link_v1_HostMessage_body_set_begin_MSGTYPE statemachined_link_v1_SetBegin
#define statemachined_link_v1_HostMessage_body_set_end_MSGTYPE statemachined_link_v1_SetEnd
#define statemachined_link_v1_HostMessage_body_graph_begin_MSGTYPE statemachined_link_v1_GraphBegin
#define statemachined_link_v1_HostMessage_body_graph_dist_MSGTYPE statemachined_link_v1_GraphDist
#define statemachined_link_v1_HostMessage_body_graph_state_MSGTYPE statemachined_link_v1_GraphState
#define statemachined_link_v1_HostMessage_body_graph_transition_MSGTYPE statemachined_link_v1_GraphTransition
#define statemachined_link_v1_HostMessage_body_graph_action_MSGTYPE statemachined_link_v1_GraphAction
#define statemachined_link_v1_HostMessage_body_graph_timer_MSGTYPE statemachined_link_v1_GraphTimer
#define statemachined_link_v1_HostMessage_body_graph_end_MSGTYPE statemachined_link_v1_GraphEnd
#define statemachined_link_v1_HostMessage_body_configure_MSGTYPE statemachined_link_v1_Configure
#define statemachined_link_v1_HostMessage_body_start_MSGTYPE statemachined_link_v1_Start
#define statemachined_link_v1_HostMessage_body_cancel_MSGTYPE statemachined_link_v1_Cancel
#define statemachined_link_v1_HostMessage_body_ping_MSGTYPE statemachined_link_v1_Ping
#define statemachined_link_v1_HostMessage_body_state_MSGTYPE statemachined_link_v1_StateRequest
#define statemachined_link_v1_HostMessage_body_wiring_MSGTYPE statemachined_link_v1_Wiring
#define statemachined_link_v1_HostMessage_body_timers_MSGTYPE statemachined_link_v1_Timers
#define statemachined_link_v1_HostMessage_body_pins_MSGTYPE statemachined_link_v1_Pins
#define statemachined_link_v1_HostMessage_body_autorun_MSGTYPE statemachined_link_v1_Autorun
#define statemachined_link_v1_HostMessage_body_save_MSGTYPE statemachined_link_v1_Save

#define statemachined_link_v1_DeviceMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   message_id,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   in_reply_to,       2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,hello_ack,body.hello_ack),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ack,body.ack),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,set_ok,body.set_ok),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,armed,body.armed),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,started,body.started),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,cancel_ack,body.cancel_ack),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,result_begin,body.result_begin),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,result_path,body.result_path),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,result_end,body.result_end),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,event,body.event),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,error,body.error),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,log,body.log),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,pong,body.pong),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,state_report,body.state_report),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,visit,body.visit),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,pin_map,body.pin_map),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,autorun_ok,body.autorun_ok),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,saved,body.saved),  27)
#define statemachined_link_v1_DeviceMessage_CALLBACK NULL
#define statemachined_link_v1_DeviceMessage_DEFAULT NULL
#define statemachined_link_v1_DeviceMessage_body_hello_ack_MSGTYPE statemachined_link_v1_HelloAck
#define statemachined_link_v1_DeviceMessage_body_ack_MSGTYPE statemachined_link_v1_Ack
#define statemachined_link_v1_DeviceMessage_body_set_ok_MSGTYPE statemachined_link_v1_SetOk
#define statemachined_link_v1_DeviceMessage_body_armed_MSGTYPE statemachined_link_v1_Armed
#define statemachined_link_v1_DeviceMessage_body_started_MSGTYPE statemachined_link_v1_Started
#define statemachined_link_v1_DeviceMessage_body_cancel_ack_MSGTYPE statemachined_link_v1_CancelAck
#define statemachined_link_v1_DeviceMessage_body_result_begin_MSGTYPE statemachined_link_v1_ResultBegin
#define statemachined_link_v1_DeviceMessage_body_result_path_MSGTYPE statemachined_link_v1_ResultPath
#define statemachined_link_v1_DeviceMessage_body_result_end_MSGTYPE statemachined_link_v1_ResultEnd
#define statemachined_link_v1_DeviceMessage_body_event_MSGTYPE statemachined_link_v1_Event
#define statemachined_link_v1_DeviceMessage_body_error_MSGTYPE statemachined_link_v1_Error
#define statemachined_link_v1_DeviceMessage_body_log_MSGTYPE statemachined_link_v1_Log
#define statemachined_link_v1_DeviceMessage_body_pong_MSGTYPE statemachined_link_v1_Pong
#define statemachined_link_v1_DeviceMessage_body_state_report_MSGTYPE statemachined_link_v1_StateReport
#define statemachined_link_v1_DeviceMessage_body_visit_MSGTYPE statemachined_link_v1_Visit
#define statemachined_link_v1_DeviceMessage_body_pin_map_MSGTYPE statemachined_link_v1_PinMap
#define statemachined_link_v1_DeviceMessage_body_autorun_ok_MSGTYPE statemachined_link_v1_AutorunOk
#define statemachined_link_v1_DeviceMessage_body_saved_MSGTYPE statemachined_link_v1_Saved

#define statemachined_link_v1_Hello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto,             1) \
X(a, STATIC,   SINGULAR, UINT64,   seed,              2)
#define statemachined_link_v1_Hello_CALLBACK NULL
#define statemachined_link_v1_Hello_DEFAULT NULL

#define statemachined_link_v1_SetBegin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   set_version,       1) \
X(a, STATIC,   SINGULAR, UINT32,   n_graphs,          2)
#define statemachined_link_v1_SetBegin_CALLBACK NULL
#define statemachined_link_v1_SetBegin_DEFAULT NULL

#define statemachined_link_v1_SetEnd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   n_states,          1) \
X(a, STATIC,   SINGULAR, UINT32,   n_transitions,     2) \
X(a, STATIC,   SINGULAR, UINT32,   n_output_actions,   3) \
X(a, STATIC,   SINGULAR, UINT32,   checksum,          4)
#define statemachined_link_v1_SetEnd_CALLBACK NULL
#define statemachined_link_v1_SetEnd_DEFAULT NULL

#define statemachined_link_v1_GraphBegin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   slot,              1) \
X(a, STATIC,   SINGULAR, UINT32,   n_states,          2) \
X(a, STATIC,   SINGULAR, UINT32,   entry,             3)
#define statemachined_link_v1_GraphBegin_CALLBACK NULL
#define statemachined_link_v1_GraphBegin_DEFAULT NULL

#define statemachined_link_v1_GraphDist_FIELDLIST(X, a_) \
X(a_, STATIC,   SINGULAR, UINT32,   i,                 1) \
X(a_, STATIC,   SINGULAR, UENUM,    kind,              2) \
X(a_, STATIC,   SINGULAR, SINT32,   a,                 3) \
X(a_, STATIC,   SINGULAR, SINT32,   b,                 4) \
X(a_, STATIC,   SINGULAR, SINT32,   c,                 5) \
X(a_, STATIC,   REPEATED, SINT32,   opts,              6) \
X(a_, STATIC,   REPEATED, UINT32,   weights,           7)
#define statemachined_link_v1_GraphDist_CALLBACK NULL
#define statemachined_link_v1_GraphDist_DEFAULT NULL

#define statemachined_link_v1_Timeout_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dist,              1) \
X(a, STATIC,   SINGULAR, UINT32,   target,            2)
#define statemachined_link_v1_Timeout_CALLBACK NULL
#define statemachined_link_v1_Timeout_DEFAULT NULL

#define statemachined_link_v1_GraphState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   i,                 1) \
X(a, STATIC,   OPTIONAL, SINT32,   terminal,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timeout,           3) \
X(a, STATIC,   OPTIONAL, UINT32,   relight,           4)
#define statemachined_link_v1_GraphState_CALLBACK NULL
#define statemachined_link_v1_GraphState_DEFAULT NULL
#define statemachined_link_v1_GraphState_timeout_MSGTYPE statemachined_link_v1_Timeout

#define statemachined_link_v1_GraphTransition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   all,               1) \
X(a, STATIC,   SINGULAR, UINT32,   any,               2) \
X(a, STATIC,   SINGULAR, UINT32,   none,              3) \
X(a, STATIC,   SINGULAR, UINT32,   target,            4) \
X(a, STATIC,   OPTIONAL, UINT32,   hold,              5) \
X(a, STATIC,   SINGULAR, BOOL,     level,             6)
#define statemachined_link_v1_GraphTransition_CALLBACK NULL
#define statemachined_link_v1_GraphTransition_DEFAULT NULL

#define statemachined_link_v1_GraphAction_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    on,                1) \
X(a, STATIC,   SINGULAR, UINT32,   line,              2) \
X(a, STATIC,   SINGULAR, UENUM,    kind,              3) \
X(a, STATIC,   SINGULAR, UINT32,   ms,                4) \
X(a, STATIC,   SINGULAR, UINT32,   timer,             5)
#define statemachined_link_v1_GraphAction_CALLBACK NULL
#define statemachined_link_v1_GraphAction_DEFAULT NULL

#define statemachined_link_v1_GraphTimer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   i,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   width,             2) \
X(a, STATIC,   OPTIONAL, UINT32,   delay,             3) \
X(a, STATIC,   OPTIONAL, UINT32,   gap,               4) \
X(a, STATIC,   OPTIONAL, UINT32,   line,              5) \
X(a, STATIC,   OPTIONAL, UINT32,   loops,             6) \
X(a, STATIC,   SINGULAR, UINT32,   all,               7) \
X(a, STATIC,   SINGULAR, UINT32,   any,               8) \
X(a, STATIC,   SINGULAR, UINT32,   none,              9) \
X(a, STATIC,   SINGULAR, BOOL,     active_low,       10) \
X(a, STATIC,   SINGULAR, BOOL,     trial_bound,      11)
#define statemachined_link_v1_GraphTimer_CALLBACK NULL
#define statemachined_link_v1_GraphTimer_DEFAULT NULL

#define statemachined_link_v1_GraphEnd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   n_transitions,     1) \
X(a, STATIC,   SINGULAR, UINT32,   n_output_actions,   2)
#define statemachined_link_v1_GraphEnd_CALLBACK NULL
#define statemachined_link_v1_GraphEnd_DEFAULT NULL

#define statemachined_link_v1_Patch_FIELDLIST(X, a_) \
X(a_, STATIC,   SINGULAR, UINT32,   i,                 1) \
X(a_, STATIC,   OPTIONAL, SINT32,   a,                 2) \
X(a_, STATIC,   OPTIONAL, SINT32,   b,                 3) \
X(a_, STATIC,   OPTIONAL, SINT32,   c,                 4)
#define statemachined_link_v1_Patch_CALLBACK NULL
#define statemachined_link_v1_Patch_DEFAULT NULL

#define statemachined_link_v1_Configure_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   set_version,       2) \
X(a, STATIC,   SINGULAR, UINT32,   graph_index,       3) \
X(a, STATIC,   SINGULAR, SINT32,   cap_ms,            4) \
X(a, STATIC,   SINGULAR, UENUM,    start,             5) \
X(a, STATIC,   OPTIONAL, UINT32,   start_line,        6) \
X(a, STATIC,   OPTIONAL, UINT32,   timers,            7) \
X(a, STATIC,   REPEATED, MESSAGE,  patch,             8)
#define statemachined_link_v1_Configure_CALLBACK NULL
#define statemachined_link_v1_Configure_DEFAULT NULL
#define statemachined_link_v1_Configure_patch_MSGTYPE statemachined_link_v1_Patch

#define statemachined_link_v1_Start_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1)
#define statemachined_link_v1_Start_CALLBACK NULL
#define statemachined_link_v1_Start_DEFAULT NULL

#define statemachined_link_v1_Cancel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            2)
#define statemachined_link_v1_Cancel_CALLBACK NULL
#define statemachined_link_v1_Cancel_DEFAULT NULL

#define statemachined_link_v1_Ping_FIELDLIST(X, a) \

#define statemachined_link_v1_Ping_CALLBACK NULL
#define statemachined_link_v1_Ping_DEFAULT NULL

#define statemachined_link_v1_StateRequest_FIELDLIST(X, a) \

#define statemachined_link_v1_StateRequest_CALLBACK NULL
#define statemachined_link_v1_StateRequest_DEFAULT NULL

#define statemachined_link_v1_Wiring_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   invert,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   enable,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   safe,              3) \
X(a, STATIC,   REPEATED, UINT32,   debounce_ms,       4)
#define statemachined_link_v1_Wiring_CALLBACK NULL
#define statemachined_link_v1_Wiring_DEFAULT NULL

#define statemachined_link_v1_Timers_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   enable,            1)
#define statemachined_link_v1_Timers_CALLBACK NULL
#define statemachined_link_v1_Timers_DEFAULT NULL

#define statemachined_link_v1_Pins_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    dir,               1)
#define statemachined_link_v1_Pins_CALLBACK NULL
#define statemachined_link_v1_Pins_DEFAULT NULL

#define statemachined_link_v1_Autorun_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   graph_index,       2) \
X(a, STATIC,   OPTIONAL, SINT32,   cap_ms,            3) \
X(a, STATIC,   OPTIONAL, UINT64,   seed,              4) \
X(a, STATIC,   OPTIONAL, UINT32,   first_trial_id,    5) \
X(a, STATIC,   OPTIONAL, BOOL,     start_now,         6)
#define statemachined_link_v1_Autorun_CALLBACK NULL
#define statemachined_link_v1_Autorun_DEFAULT NULL

#define statemachined_link_v1_Save_FIELDLIST(X, a) \

#define statemachined_link_v1_Save_CALLBACK NULL
#define statemachined_link_v1_Save_DEFAULT NULL

#define statemachined_link_v1_Caps_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   max_frame,         1) \
X(a, STATIC,   SINGULAR, UINT32,   max_states,        2) \
X(a, STATIC,   SINGULAR, UINT32,   max_transitions,   3) \
X(a, STATIC,   SINGULAR, UINT32,   max_output_actions,   4) \
X(a, STATIC,   SINGULAR, UINT32,   max_distributions,   5) \
X(a, STATIC,   SINGULAR, UINT32,   max_choice_options,   6) \
X(a, STATIC,   SINGULAR, UINT32,   max_path,          7) \
X(a, STATIC,   SINGULAR, UINT32,   max_graphs,        8) \
X(a, STATIC,   SINGULAR, UINT32,   max_timers,        9) \
X(a, STATIC,   SINGULAR, UINT32,   first_timer_line,  10)
#define statemachined_link_v1_Caps_CALLBACK NULL
#define statemachined_link_v1_Caps_DEFAULT NULL

#define statemachined_link_v1_HelloAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto,             1) \
X(a, STATIC,   SINGULAR, STRING,   board,             2) \
X(a, STATIC,   SINGULAR, STRING,   fw,                3) \
X(a, STATIC,   SINGULAR, UINT32,   n_input_lines,     4) \
X(a, STATIC,   SINGULAR, UINT32,   n_output_lines,    5) \
X(a, STATIC,   SINGULAR, UINT32,   scan_hz,           6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  caps,              7) \
X(a, STATIC,   SINGULAR, BOOL,     has_set,           8) \
X(a, STATIC,   SINGULAR, UINT32,   set_version,       9) \
X(a, STATIC,   SINGULAR, UINT32,   n_graphs,         10) \
X(a, STATIC,   SINGULAR, BOOL,     has_wiring,       11)
#define statemachined_link_v1_HelloAck_CALLBACK NULL
#define statemachined_link_v1_HelloAck_DEFAULT NULL
#define statemachined_link_v1_HelloAck_caps_MSGTYPE statemachined_link_v1_Caps

#define statemachined_link_v1_Ack_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   enable,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   n_timers,          2)
#define statemachined_link_v1_Ack_CALLBACK NULL
#define statemachined_link_v1_Ack_DEFAULT NULL

#define statemachined_link_v1_SetOk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   set_version,       1) \
X(a, STATIC,   SINGULAR, UINT32,   n_graphs,          2) \
X(a, STATIC,   SINGULAR, UINT32,   n_states,          3) \
X(a, STATIC,   SINGULAR, UINT32,   n_transitions,     4) \
X(a, STATIC,   SINGULAR, UINT32,   n_output_actions,   5)
#define statemachined_link_v1_SetOk_CALLBACK NULL
#define statemachined_link_v1_SetOk_DEFAULT NULL

#define statemachined_link_v1_Armed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   set_version,       2) \
X(a, STATIC,   SINGULAR, UINT32,   graph_index,       3)
#define statemachined_link_v1_Armed_CALLBACK NULL
#define statemachined_link_v1_Armed_DEFAULT NULL

#define statemachined_link_v1_Started_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   at_us,             2) \
X(a, STATIC,   SINGULAR, UENUM,    by,                3) \
X(a, STATIC,   OPTIONAL, UINT32,   line,              4)
#define statemachined_link_v1_Started_CALLBACK NULL
#define statemachined_link_v1_Started_DEFAULT NULL

#define statemachined_link_v1_CancelAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1) \
X(a, STATIC,   SINGULAR, BOOL,     cancelled,         2) \
X(a, STATIC,   SINGULAR, SINT32,   outcome,           3)
#define statemachined_link_v1_CancelAck_CALLBACK NULL
#define statemachined_link_v1_CancelAck_DEFAULT NULL

#define statemachined_link_v1_StateVisit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   state,             1) \
X(a, STATIC,   SINGULAR, UENUM,    exit,              2) \
X(a, STATIC,   SINGULAR, UINT32,   transition,        3) \
X(a, STATIC,   SINGULAR, SINT32,   drawn_ms,          4) \
X(a, STATIC,   SINGULAR, UINT32,   entered_us,        5) \
X(a, STATIC,   SINGULAR, UINT32,   duration_us,       6)
#define statemachined_link_v1_StateVisit_CALLBACK NULL
#define statemachined_link_v1_StateVisit_DEFAULT NULL

#define statemachined_link_v1_ResultBegin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1) \
X(a, STATIC,   SINGULAR, SINT32,   outcome,           2) \
X(a, STATIC,   SINGULAR, UINT32,   cancel_reason,     3) \
X(a, STATIC,   SINGULAR, UINT32,   total_us,          4) \
X(a, STATIC,   SINGULAR, UINT32,   path_len,          5) \
X(a, STATIC,   SINGULAR, UINT32,   first_seq,         6) \
X(a, STATIC,   SINGULAR, UINT32,   total_visits,      7) \
X(a, STATIC,   SINGULAR, BOOL,     truncated,         8)
#define statemachined_link_v1_ResultBegin_CALLBACK NULL
#define statemachined_link_v1_ResultBegin_DEFAULT NULL

#define statemachined_link_v1_ResultPath_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   from,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  p,                 3)
#define statemachined_link_v1_ResultPath_CALLBACK NULL
#define statemachined_link_v1_ResultPath_DEFAULT NULL
#define statemachined_link_v1_ResultPath_p_MSGTYPE statemachined_link_v1_StateVisit

#define statemachined_link_v1_ResultEnd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   checksum,          2)
#define statemachined_link_v1_ResultEnd_CALLBACK NULL
#define statemachined_link_v1_ResultEnd_DEFAULT NULL

#define statemachined_link_v1_Event_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   us,                1) \
X(a, STATIC,   SINGULAR, UINT32,   word,              2)
#define statemachined_link_v1_Event_CALLBACK NULL
#define statemachined_link_v1_Event_DEFAULT NULL

#define statemachined_link_v1_Error_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   code,              1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, STATIC,   SINGULAR, STRING,   context,           3)
#define statemachined_link_v1_Error_CALLBACK NULL
#define statemachined_link_v1_Error_DEFAULT NULL

#define statemachined_link_v1_Log_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   level,             1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define statemachined_link_v1_Log_CALLBACK NULL
#define statemachined_link_v1_Log_DEFAULT NULL

#define statemachined_link_v1_Pong_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   up_us,             1) \
X(a, STATIC,   SINGULAR, UINT32,   us,                2)
#define statemachined_link_v1_Pong_CALLBACK NULL
#define statemachined_link_v1_Pong_DEFAULT NULL

#define statemachined_link_v1_GraphReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_set,           1) \
X(a, STATIC,   SINGULAR, UINT32,   set_version,       2) \
X(a, STATIC,   SINGULAR, UINT32,   n_graphs,          3) \
X(a, STATIC,   SINGULAR, UINT32,   index,             4)
#define statemachined_link_v1_GraphReport_CALLBACK NULL
#define statemachined_link_v1_GraphReport_DEFAULT NULL

#define statemachined_link_v1_IoReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   in,                1) \
X(a, STATIC,   SINGULAR, UINT32,   out,               2)
#define statemachined_link_v1_IoReport_CALLBACK NULL
#define statemachined_link_v1_IoReport_DEFAULT NULL

#define statemachined_link_v1_ScanReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   hz,                1) \
X(a, STATIC,   SINGULAR, UINT32,   overruns,          2) \
X(a, STATIC,   SINGULAR, UINT32,   worst_gap,         3) \
X(a, STATIC,   SINGULAR, UINT32,   tx_stalls,         4) \
X(a, STATIC,   SINGULAR, UINT32,   visits_dropped,    5) \
X(a, STATIC,   SINGULAR, UINT32,   timers_enabled,    6) \
X(a, STATIC,   SINGULAR, UINT32,   timers_running,    7)
#define statemachined_link_v1_ScanReport_CALLBACK NULL
#define statemachined_link_v1_ScanReport_DEFAULT NULL

#define statemachined_link_v1_StateReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   link_state,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  graph,             2) \
X(a, STATIC,   SINGULAR, BOOL,     has_wiring,        3) \
X(a, STATIC,   SINGULAR, BOOL,     autorun,           4) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          5) \
X(a, STATIC,   SINGULAR, BOOL,     running,           6) \
X(a, STATIC,   SINGULAR, UINT32,   current_state,     7) \
X(a, STATIC,   SINGULAR, UINT32,   up_us,             8) \
X(a, STATIC,   SINGULAR, UINT32,   dropped_lines,     9) \
X(a, STATIC,   SINGULAR, UINT32,   bad_lines,        10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  io,               11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scan,             12)
#define statemachined_link_v1_StateReport_CALLBACK NULL
#define statemachined_link_v1_StateReport_DEFAULT NULL
#define statemachined_link_v1_StateReport_graph_MSGTYPE statemachined_link_v1_GraphReport
#define statemachined_link_v1_StateReport_io_MSGTYPE statemachined_link_v1_IoReport
#define statemachined_link_v1_StateReport_scan_MSGTYPE statemachined_link_v1_ScanReport

#define statemachined_link_v1_Visit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trial_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  v,                 3)
#define statemachined_link_v1_Visit_CALLBACK NULL
#define statemachined_link_v1_Visit_DEFAULT NULL
#define statemachined_link_v1_Visit_v_MSGTYPE statemachined_link_v1_StateVisit

#define statemachined_link_v1_PinMap_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    dir,               1) \
X(a, STATIC,   SINGULAR, UINT32,   n,                 2) \
X(a, STATIC,   REPEATED, STRING,   pins,              3)
#define statemachined_link_v1_PinMap_CALLBACK NULL
#define statemachined_link_v1_PinMap_DEFAULT NULL

#define statemachined_link_v1_AutorunOk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, BOOL,     active,            2) \
X(a, STATIC,   SINGULAR, UINT32,   graph_index,       3) \
X(a, STATIC,   SINGULAR, SINT32,   cap_ms,            4) \
X(a, STATIC,   SINGULAR, UINT32,   next_trial_id,     5)
#define statemachined_link_v1_AutorunOk_CALLBACK NULL
#define statemachined_link_v1_AutorunOk_DEFAULT NULL

#define statemachined_link_v1_Saved_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_set,           1) \
X(a, STATIC,   SINGULAR, UINT32,   set_version,       2) \
X(a, STATIC,   SINGULAR, BOOL,     autorun,           3) \
X(a, STATIC,   SINGULAR, UINT32,   write_count,       4) \
X(a, STATIC,   SINGULAR, BOOL,     written,           5)
#define statemachined_link_v1_Saved_CALLBACK NULL
#define statemachined_link_v1_Saved_DEFAULT NULL

extern const pb_msgdesc_t statemachined_link_v1_HostMessage_msg;
extern const pb_msgdesc_t statemachined_link_v1_DeviceMessage_msg;
extern const pb_msgdesc_t statemachined_link_v1_Hello_msg;
extern const pb_msgdesc_t statemachined_link_v1_SetBegin_msg;
extern const pb_msgdesc_t statemachined_link_v1_SetEnd_msg;
extern const pb_msgdesc_t statemachined_link_v1_GraphBegin_msg;
extern const pb_msgdesc_t statemachined_link_v1_GraphDist_msg;
extern const pb_msgdesc_t statemachined_link_v1_Timeout_msg;
extern const pb_msgdesc_t statemachined_link_v1_GraphState_msg;
extern const pb_msgdesc_t statemachined_link_v1_GraphTransition_msg;
extern const pb_msgdesc_t statemachined_link_v1_GraphAction_msg;
extern const pb_msgdesc_t statemachined_link_v1_GraphTimer_msg;
extern const pb_msgdesc_t statemachined_link_v1_GraphEnd_msg;
extern const pb_msgdesc_t statemachined_link_v1_Patch_msg;
extern const pb_msgdesc_t statemachined_link_v1_Configure_msg;
extern const pb_msgdesc_t statemachined_link_v1_Start_msg;
extern const pb_msgdesc_t statemachined_link_v1_Cancel_msg;
extern const pb_msgdesc_t statemachined_link_v1_Ping_msg;
extern const pb_msgdesc_t statemachined_link_v1_StateRequest_msg;
extern const pb_msgdesc_t statemachined_link_v1_Wiring_msg;
extern const pb_msgdesc_t statemachined_link_v1_Timers_msg;
extern const pb_msgdesc_t statemachined_link_v1_Pins_msg;
extern const pb_msgdesc_t statemachined_link_v1_Autorun_msg;
extern const pb_msgdesc_t statemachined_link_v1_Save_msg;
extern const pb_msgdesc_t statemachined_link_v1_Caps_msg;
extern const pb_msgdesc_t statemachined_link_v1_HelloAck_msg;
extern const pb_msgdesc_t statemachined_link_v1_Ack_msg;
extern const pb_msgdesc_t statemachined_link_v1_SetOk_msg;
extern const pb_msgdesc_t statemachined_link_v1_Armed_msg;
extern const pb_msgdesc_t statemachined_link_v1_Started_msg;
extern const pb_msgdesc_t statemachined_link_v1_CancelAck_msg;
extern const pb_msgdesc_t statemachined_link_v1_StateVisit_msg;
extern const pb_msgdesc_t statemachined_link_v1_ResultBegin_msg;
extern const pb_msgdesc_t statemachined_link_v1_ResultPath_msg;
extern const pb_msgdesc_t statemachined_link_v1_ResultEnd_msg;
extern const pb_msgdesc_t statemachined_link_v1_Event_msg;
extern const pb_msgdesc_t statemachined_link_v1_Error_msg;
extern const pb_msgdesc_t statemachined_link_v1_Log_msg;
extern const pb_msgdesc_t statemachined_link_v1_Pong_msg;
extern const pb_msgdesc_t statemachined_link_v1_GraphReport_msg;
extern const pb_msgdesc_t statemachined_link_v1_IoReport_msg;
extern const pb_msgdesc_t statemachined_link_v1_ScanReport_msg;
extern const pb_msgdesc_t statemachined_link_v1_StateReport_msg;
extern const pb_msgdesc_t statemachined_link_v1_Visit_msg;
extern const pb_msgdesc_t statemachined_link_v1_PinMap_msg;
extern const pb_msgdesc_t statemachined_link_v1_AutorunOk_msg;
extern const pb_msgdesc_t statemachined_link_v1_Saved_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define statemachined_link_v1_HostMessage_fields &statemachined_link_v1_HostMessage_msg
#define statemachined_link_v1_DeviceMessage_fields &statemachined_link_v1_DeviceMessage_msg
#define statemachined_link_v1_Hello_fields &statemachined_link_v1_Hello_msg
#define statemachined_link_v1_SetBegin_fields &statemachined_link_v1_SetBegin_msg
#define statemachined_link_v1_SetEnd_fields &statemachined_link_v1_SetEnd_msg
#define statemachined_link_v1_GraphBegin_fields &statemachined_link_v1_GraphBegin_msg
#define statemachined_link_v1_GraphDist_fields &statemachined_link_v1_GraphDist_msg
#define statemachined_link_v1_Timeout_fields &statemachined_link_v1_Timeout_msg
#define statemachined_link_v1_GraphState_fields &statemachined_link_v1_GraphState_msg
#define statemachined_link_v1_GraphTransition_fields &statemachined_link_v1_GraphTransition_msg
#define statemachined_link_v1_GraphAction_fields &statemachined_link_v1_GraphAction_msg
#define statemachined_link_v1_GraphTimer_fields &statemachined_link_v1_GraphTimer_msg
#define statemachined_link_v1_GraphEnd_fields &statemachined_link_v1_GraphEnd_msg
#define statemachined_link_v1_Patch_fields &statemachined_link_v1_Patch_msg
#define statemachined_link_v1_Configure_fields &statemachined_link_v1_Configure_msg
#define statemachined_link_v1_Start_fields &statemachined_link_v1_Start_msg
#define statemachined_link_v1_Cancel_fields &statemachined_link_v1_Cancel_msg
#define statemachined_link_v1_Ping_fields &statemachined_link_v1_Ping_msg
#define statemachined_link_v1_StateRequest_fields &statemachined_link_v1_StateRequest_msg
#define statemachined_link_v1_Wiring_fields &statemachined_link_v1_Wiring_msg
#define statemachined_link_v1_Timers_fields &statemachined_link_v1_Timers_msg
#define statemachined_link_v1_Pins_fields &statemachined_link_v1_Pins_msg
#define statemachined_link_v1_Autorun_fields &statemachined_link_v1_Autorun_msg
#define statemachined_link_v1_Save_fields &statemachined_link_v1_Save_msg
#define statemachined_link_v1_Caps_fields &statemachined_link_v1_Caps_msg
#define statemachined_link_v1_HelloAck_fields &statemachined_link_v1_HelloAck_msg
#define statemachined_link_v1_Ack_fields &statemachined_link_v1_Ack_msg
#define statemachined_link_v1_SetOk_fields &statemachined_link_v1_SetOk_msg
#define statemachined_link_v1_Armed_fields &statemachined_link_v1_Armed_msg
#define statemachined_link_v1_Started_fields &statemachined_link_v1_Started_msg
#define statemachined_link_v1_CancelAck_fields &statemachined_link_v1_CancelAck_msg
#define statemachined_link_v1_StateVisit_fields &statemachined_link_v1_StateVisit_msg
#define statemachined_link_v1_ResultBegin_fields &statemachined_link_v1_ResultBegin_msg
#define statemachined_link_v1_ResultPath_fields &statemachined_link_v1_ResultPath_msg
#define statemachined_link_v1_ResultEnd_fields &statemachined_link_v1_ResultEnd_msg
#define statemachined_link_v1_Event_fields &statemachined_link_v1_Event_msg
#define statemachined_link_v1_Error_fields &statemachined_link_v1_Error_msg
#define statemachined_link_v1_Log_fields &statemachined_link_v1_Log_msg
#define statemachined_link_v1_Pong_fields &statemachined_link_v1_Pong_msg
#define statemachined_link_v1_GraphReport_fields &statemachined_link_v1_GraphReport_msg
#define statemachined_link_v1_IoReport_fields &statemachined_link_v1_IoReport_msg
#define statemachined_link_v1_ScanReport_fields &statemachined_link_v1_ScanReport_msg
#define statemachined_link_v1_StateReport_fields &statemachined_link_v1_StateReport_msg
#define statemachined_link_v1_Visit_fields &statemachined_link_v1_Visit_msg
#define statemachined_link_v1_PinMap_fields &statemachined_link_v1_PinMap_msg
#define statemachined_link_v1_AutorunOk_fields &statemachined_link_v1_AutorunOk_msg
#define statemachined_link_v1_Saved_fields &statemachined_link_v1_Saved_msg

/* Maximum encoded size of messages (where known) */
#define STATEMACHINED_LINK_V1_STATEMACHINED_LINK_V1_LINK_PB_H_MAX_SIZE statemachined_link_v1_DeviceMessage_size
#define statemachined_link_v1_Ack_size           12
#define statemachined_link_v1_Armed_size         18
#define statemachined_link_v1_AutorunOk_size     22
#define statemachined_link_v1_Autorun_size       33
#define statemachined_link_v1_CancelAck_size     14
#define statemachined_link_v1_Cancel_size        8
#define statemachined_link_v1_Caps_size          60
#define statemachined_link_v1_Configure_size     246
#define statemachined_link_v1_DeviceMessage_size 500
#define statemachined_link_v1_Error_size         171
#define statemachined_link_v1_Event_size         12
#define statemachined_link_v1_GraphAction_size   22
#define statemachined_link_v1_GraphBegin_size    18
#define statemachined_link_v1_GraphDist_size     410
#define statemachined_link_v1_GraphEnd_size      12
#define statemachined_link_v1_GraphReport_size   20
#define statemachined_link_v1_GraphState_size    32
#define statemachined_link_v1_GraphTimer_size    58
#define statemachined_link_v1_GraphTransition_size 32
#define statemachined_link_v1_HelloAck_size      176
#define statemachined_link_v1_Hello_size         17
#define statemachined_link_v1_HostMessage_size   417
#define statemachined_link_v1_IoReport_size      12
#define statemachined_link_v1_Log_size           106
#define statemachined_link_v1_Patch_size         24
#define statemachined_link_v1_PinMap_size        296
#define statemachined_link_v1_Ping_size          0
#define statemachined_link_v1_Pins_size          2
#define statemachined_link_v1_Pong_size          12
#define statemachined_link_v1_ResultBegin_size   44
#define statemachined_link_v1_ResultEnd_size     12
#define statemachined_link_v1_ResultPath_size    488
#define statemachined_link_v1_Save_size          0
#define statemachined_link_v1_Saved_size         18
#define statemachined_link_v1_ScanReport_size    42
#define statemachined_link_v1_SetBegin_size      12
#define statemachined_link_v1_SetEnd_size        24
#define statemachined_link_v1_SetOk_size         30
#define statemachined_link_v1_Start_size         6
#define statemachined_link_v1_Started_size       20
#define statemachined_link_v1_StateReport_size   122
#define statemachined_link_v1_StateRequest_size  0
#define statemachined_link_v1_StateVisit_size    32
#define statemachined_link_v1_Timeout_size       12
#define statemachined_link_v1_Timers_size        6
#define statemachined_link_v1_Visit_size         46
#define statemachined_link_v1_Wiring_size        210

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
